### ISSUE TITLE
 unknown error when sending audio message

### ISSUE THREAD

**Issue by mneysa** [line/line-bot-sdk-php#106]
Hello, so i'm trying to send an audio message in my bot
i used this link for the audio -> [audio](https://linegames.littleqiwi.com/temp/output.m4a)

the message is sent successfully without any error, but when i tried to play the audio, it said "An unknown error occured. please try again later"

the other message such as images and videos can be opened without any problem so i guess this is not the SNI problem ?

here's my snippet of audioMessage code

`              
$audioMessageBuilder = new \LINE\LINEBot\MessageBuilder\AudioMessageBuilder("https://linegames.littleqiwi.com/temp/output.m4a",30000);
`
` $response = $this->bot->replyMessage($replyToken,$audioMessageBuilder);
`

Please help me, thanks a lot !

**Comment by Vaduz** [comment]
You didn't get any error on sending the message, so the issue doesn't relate this SDK.
But I took a look, the server is returning wrong content type for that file.
It should be `audio/mp4`.

**Comment by mneysa** [comment]
Hey thanks for replying so fast :)

Okay, so i just add new mime type in my apache configuration for the format, so now the audio mime type is audio/mp4.. but it still not working 

I know that this is not the right place to ask, but please kindly help me hehe :)

Thanks a lot

**Comment by Vaduz** [comment]
It looks like this is SNI issue. Try to open the message on the iOS device. Or host that file on the other server that doesn't support SNI.
https://github.com/line/line-bot-faq#why-doesnt-my-audio-video-or-image-message-display-properly-on-android-devices
