### ISSUE TITLE
how to get latitude and longitude from user location?

### ISSUE THREAD

**Issue by andreutomo** [line/line-bot-sdk-php#112]
{
    "type": "location",
    "title": "my location",
    "address": "abcdefghijk",
    "latitude": 35.65910807942215,
    "longitude": 139.70372892916203
}

my code like this
`if($event['type'] == 'message'){
 if($event['message']['type'] == 'location'){
   $message = $event['message']['latitude'];
   $textMessageBuilder = new textMessageBuilder($message);
   $this->bot->replyMessage($event['replyToken'], $textMessageBuilder);
      }
    } 
`
if i send location, the bot not response.

**Comment by lintangtimur** [comment]
im using php line sdk version 2.3
```php
if ($event instanceof LocationMessage) 
{
   $bot->replyText($event->getReplyToken(), "Latitude: {$event->getLatitude()}, Longtitude: {$event->getLongitude()}");
 }
```
then it will reply to me with format:
Latitude: -6.992461, Longtitude: 110.40065
