### ISSUE TITLE
how to make interactive reply

### ISSUE THREAD

**Issue by lintangtimur** [line/line-bot-sdk-php#113]
consider i want to make like this:
user type: "submit"
**bot reply**: "input your title"
user type: "example title blabla"
**bot reply**: "now input your message body"
user type: "lorem ipsum ..... "
**bot reply**: "thanks " and then bot do some action

how to store that variable when chatting

**Comment by Vaduz** [comment]
The messages are all text type. So just reply that message. This SDK includes example implementation like kitchen sink that may help you. You need to store the state spicified by the user id on your applocation. And handle the response message whatever you want.
