### ISSUE TITLE
SSL certificate problem

### ISSUE THREAD

**Issue by celaenasardothien** [line/line-bot-sdk-php#116]
hello.

i was exploring the sdk and tried out the push message code, but there was an error:

Uncaught exception 'LINE\LINEBot\Exception\CurlExecutionException' with message 'SSL certificate problem: unable to get local issuer certificate'

pls help. thank you

**Comment by tokuhirom** [comment]
It's not an SDK's problem. There's an issue with your PHP configuration(maybe).

ref. https://stackoverflow.com/questions/28858351/php-ssl-certificate-error-unable-to-get-local-issuer-certificate

**Comment by celaenasardothien** [comment]
you are right. can help me with webhooks? i don't understand it that much.

**Comment by tokuhirom** [comment]
@celaenasardothien sorry, we can't support problems with PHP itself.
You can ask questions in any PHP forum.

**Comment by paulinaops** [comment]
hello. can i ask again. can i use examples in this sdk on codeigniter? thanks.
