### ISSUE TITLE
line-bot-sdk-tiny

### ISSUE THREAD

**Issue by paulinaops** [line/line-bot-sdk-php#117]
does line-bot-sdk-tiny also need webhooks? sorry, i am a beginner at this. ty.

**Comment by Vaduz** [comment]
Yes.  See `echo_bot.php`. It's the example implementation of `line-bot-sdk-tiny`.  You need is just set that `echo_bot.php` as the entrypoint of your application then should work "echo bot" instantly.

**Comment by paulinaops** [comment]
thanks. is it possible to map the line ID to user ID? will i be able to get the user ID thru the line ID.

**Comment by Vaduz** [comment]
Nope. We are not providing such API for now.
