### ISSUE TITLE
Add some feature like unofficial api

### ISSUE THREAD

**Issue by lintangtimur** [line/line-bot-sdk-php#119]
i found some interesting features like 
- autolike post, and comment
- know who just saw, like LINE lite
- protect group from kicker, auto cancel / join
- ...
https://github.com/TobyG74/BotToby
https://github.com/alfathdirk/LIN3-TCR

whether the above feature can be added in the SDK?

sorry if my english is bad

**Comment by tokuhirom** [comment]
We don't provide APIs for these features.... We can't provide SDK methods for these methods.
