### ISSUE TITLE
Finding Out the Abnormal HTTP Status Code

### ISSUE THREAD

**Issue by Naufal-FR** [line/line-bot-sdk-php#120]
So just recently around 6 hours ago my BOT stopped working. I tried verifying the webhook via LINE Dev and got this response 

![image](https://user-images.githubusercontent.com/24642717/33198150-fc80587c-d11b-11e7-96a6-91cc75a05844.png)

Not really sure what happen and wonder what could possibly be the case.
NB : I'm using the line-tiny version at the moment since my hosting doesn't allow for easy composer installation.

**Comment by tokuhirom** [comment]
This message indicates your HTTP server responses abnormal status code.
In this case, your HTTP server must return status code 200, but your server's return code is not 200.

Then, you need to check your server's access log.

**Comment by hiepnsx** [comment]
If your code doesn't have problem, check Channel secret and Channel access token. 
If it doesn't work, try issue new Channel access token and set again.
Hope this helps.

**Comment by suhailgupta03** [comment]
It does not work for me. I am returning HTTP Status Code 200 and have verified from the sample CURL. Don't know why it does not work with LINE

**Comment by suhailgupta03** [comment]
It finally worked for me. Had registered a GET method instead of POST. Works fine with POST. The error message could have been more illustrating.
