### ISSUE TITLE
how to run tests/ in windows

### ISSUE THREAD

**Issue by lintangtimur** [line/line-bot-sdk-php#124]
how to run tests in windows, i just download req_mirror for windows, and i run it on port 80, when i run tests folder, this is the following result

`req_mirror server is not available. Please try to execute `make install-devtool`

**windows 10** 64bit

**Comment by Vaduz** [comment]
It's not able to run test on Windows environment because `req_mirror` doesn't support that platform for now.

**Comment by lintangtimur** [comment]
so if i want to make a pull request with require some test, it can't?

**Comment by Vaduz** [comment]
No, you can’t unfortunately. All p-r is automatically tested by the system though.

**Comment by lintangtimur** [comment]
wait, but in their releases, there was:

> req_mirror_windows_386_0.0.1
> req_mirror_windows_amd64_0.0.1

**Comment by tokuhirom** [comment]
Is this issue resolved by https://github.com/line/line-bot-sdk-php/pull/127?

**Comment by tokuhirom** [comment]
I guess the issue was resolved by #127. If this issue still exists in the current implementation, please re-open it.
