### ISSUE TITLE
Become UnknownEvent when adding friends @Windows10

### ISSUE THREAD

**Issue by sh-ogawa** [line/line-bot-sdk-php#125]
At the time of follow, I expect that the actual state of event is LINE\LINEBot\Event\FollowEvent
, but it will be LINE\LINEBot\Event\UnknownEvent.
I can get FollowEvent on Linux, but not on Windows 10.

[environment]
・OS : Windows10
・PHP：7.1.5
・line-bot-sdk：2.3

[Source]
$events = $bot->parseEventRequest($request->getContent(), $signature);
foreach($events as $event) {
  ・・・
  // $event is UnknownEvent at adding friend my line@
}

[Log]
[2017-12-12 09:09:25] local.DEBUG: LINE\LINEBot\Event\UnknownEvent  
[2017-12-12 09:09:25] local.WARNING: Unknown event. [LINE\LINEBot\Event\UnknownEvent] {"body":{"type":"follow","replyToken":"d5d9497e7ddd4ad188a9335786ed3a49","source":{"userId":"Uc7f34002896a1731022b5bXXXXXXX","type":"user"},"timestamp":1513069764773}}

**Comment by Vaduz** [comment]
It's not able to run test on Windows environment because `req_mirror` doesn't support that platform for now.

**Comment by Vaduz** [comment]
I don't get why you get different result from same code. Can I see trace log from xdebug? It could be PHP problem if it's really happened.

**Comment by sh-ogawa** [comment]
Sorry, LINE\LINEBot\Event\Parser\EventRequestParser::eventType2class was changed while I was unaware.
composer re-import line-sdk and confirmed that it operates normally.
