### ISSUE TITLE
An error occurred when sending the webhook.

### ISSUE THREAD

**Issue by shirakun** [line/line-bot-sdk-php#126]
The problem has been solved
After I added the complete certificate chain, it began to work
@Vaduz Thank you for your reply

---------------------------------------------------------------------------------------------
When I set up webhook's URL, I click Verify
It prompts An error occurred when sending the webhook.
My web site is https://ssl.ni-co.moe/
This is the certificate used by ssl.ni-co.moe
![image](https://i.imgur.com/7AhKsiu.png)
![image](https://i.imgur.com/RZ58gf5.png)

----------------------------------------------------------------------------------------------
I deployed a test service a month ago, and I didn't have this problem.
The URL of the test server is https://line.bot.ni-co.moe
This is the certificate used by line.bot.ni-co.moe
![image](https://i.imgur.com/wdQpRsh.png)
![image](https://i.imgur.com/L80dJa2.png)

What is the reason for ssl.ni-co.moe validation failure?

**Comment by Vaduz** [comment]
Please check your CA is on this CA list.
https://developers.line.me/media/messaging-api/build-bot/ca_root_v2.txt
