### ISSUE TITLE
Test can not run on Windows environment

### ISSUE THREAD

**Issue by Vaduz** [line/line-bot-sdk-php#132]
This SDK invokes *nix specific commands in `CurlHTTPClientTest`.

**Comment by tokuhirom** [comment]
Related #124

**Comment by tkgauri** [comment]
@moririnson could you check if tests are working fine on Windows environment? Thanks!

**Comment by Vaduz** [comment]
https://docs.travis-ci.com/user/reference/windows/

**Comment by Vaduz** [comment]
We changed to skip this test
