### ISSUE TITLE
selfbot

### ISSUE THREAD

**Issue by kiamads** [line/line-bot-sdk-php#134]
## Do this before creating an issue

- Check our [developer documentation](https://developers.line.me/en/docs/) and [FAQ](https://developers.line.me/en/faq/messaging-api/) page for more information on LINE bots and the Messaging API
- Make sure your issue is **related to** the LINE Bot SDK. For general questions or issues about LINE bots, create an issue on the [LINE Platform feedback](https://github.com/line/line-platform-feedback) repository. Note that we don't provide technical support.

## When creating an issue

- Provide detailed information about the issue you had with the SDK
- Provide logs if possible

**Comment by kazuki-ma** [comment]
miss submission? Closing~.
