### ISSUE TITLE
Why Class CurlHTTPClient not found ?

### ISSUE THREAD

**Issue by RizkaOMG** [line/line-bot-sdk-php#135]
I try make simple message with line bot php sdk but when run php file it sho some error like **Fatal error: Uncaught Error: Class 'LINE\LINEBot\HTTPClient\CurlHTTPClient' not found in /storage/ssd2/404/4311404/public_html/test.php:4 Stack trace: #0 {main} thrown in /storage/ssd2/404/4311404/public_html/test.php on line 4**
My php like this 
```
<?php
include 'LINE/LINEBot.php';

$httpClient = new \LINE\LINEBot\HTTPClient\CurlHTTPClient('*****');
$bot = new \LINE\LINEBot($httpClient, ['channelSecret' => '*****']);

$textMessageBuilder = new \LINE\LINEBot\MessageBuilder\TextMessageBuilder('Coba Text');
$response = $bot->pushMessage('08123456789', $textMessageBuilder);

echo $response->getHTTPStatus() . ' ' . $response->getRawBody();
?>
```
Where is wrong from my code ? Thanks.

**Comment by lintangtimur** [comment]
```php
require "vendor/autoload.php";
```

**Comment by RizkaOMG** [comment]
400 {"message":"The property, 'to', in the request body is invalid (line: -, column: -)"} i have error like this. Is  number incorrect ?

**Comment by lintangtimur** [comment]
can you provide your code?

**Comment by kazuki-ma** [comment]
@RizkaOMG

userID in `to` poperty is not telephone number.

see https://github.com/line/line-bot-sdk-java/issues/176#issuecomment-359173276
