### ISSUE TITLE
How to know reply token?

### ISSUE THREAD

**Issue by RizkaOMG** [line/line-bot-sdk-php#137]
Hy, how to know reply token in PHP ? Thanks :D

**Comment by utatti** [comment]
Hi,

There are specific events which contains a `replyToken` property in its body. For the list of the reply-able event types, please refer to the [official API reference](https://developers.line.me/en/docs/messaging-api/reference/#webhook-event-objects).

In PHP SDK, a reply token can be retrieved by `$event->getReplyToken()`. For the code sample, please refer to the [EchoBot example](https://github.com/line/line-bot-sdk-php/blob/master/examples/EchoBot/src/LINEBot/EchoBot/Route.php).
