### ISSUE TITLE
template message not showing in Desktop version of Line Software.

### ISSUE THREAD

**Issue by chitanok** [line/line-bot-sdk-php#140]
Dear concern,

I have a bot that send Carousel template with 3 slides. It's working fine for mobile devices. But when i try to use desktop/pc version of Line, it's showing  "New Property
Check it out on your mobile
![desktop issues](https://user-images.githubusercontent.com/12227314/39102855-3733aee2-46c9-11e8-920c-2ecb035c91cd.PNG)
 device." 

Thanks and regards 
Chitano

**Comment by ncwgf** [comment]
Line desktop version currently not support template message
Which stated at documentation
https://developers.line.me/en/docs/messaging-api/reference/#template-messages
```
Note: Template messages are only supported on LINE iOS/Android versions 6.7.0 and later.
```

**Comment by chitanok** [comment]
Thanks
