### ISSUE TITLE
buttonTemplateBuilder Not Work

### ISSUE THREAD

**Issue by WilliamFalci** [line/line-bot-sdk-php#142]
Hi I want send a templateMessage specifically the ButtonTemplate (image,text,button)

This my code:

```
use LINE\LINEBot\TemplateActionBuilder\UriTemplateActionBuilder;
  use \LINE\LINEBot\MessageBuilder\TemplateBuilder\ButtonTemplateBuilder;
  use \LINE\LINEBot\MessageBuilder\TemplateMessageBuilder;

$token = "XXXXXXXXXXXXXXXXXXX";

    $httpClient = new \LINE\LINEBot\HTTPClient\CurlHTTPClient($token);
    $bot = new \LINE\LINEBot($httpClient, ['channelSecret' => 'XXXXXXXX']);

    $imageUrl = new UriTemplateActionBuilder('Prodotto', $photo);
    $buttonTemplateBuilder = new ButtonTemplateBuilder(
                       'TEST',
                       $message,
                       $photo,
                       [
                           new UriTemplateActionBuilder('BUY IT!', $url)
                       ]
                   );
    $templateMessage = new TemplateMessageBuilder('Button alt text', $buttonTemplateBuilder);
    $response = $bot->replyMessage("XXXXXXX", $templateMessage);
```

Before everything I tried to use "pushMessage" but I read the MessageTemplate can be used only in "reply" (True?) however after this I provided to get a replytoken (I modded my wh to make the bot to reply on event with the replytoken) then I tested the code up

When I go to run it I not receive any kind of error but I not receive any message on line too... someone can help me please?

**Comment by enesbyrk1** [comment]
use LINE\LINEBot\TemplateActionBuilder\UriTemplateActionBuilder;
  use \LINE\LINEBot\MessageBuilder\TemplateBuilder\ButtonTemplateBuilder;
  use \LINE\LINEBot\MessageBuilder\TemplateMessageBuilder;

$token = "XXXXXXXXXXXXXXXXXXX";

    $httpClient = new \LINE\LINEBot\HTTPClient\CurlHTTPClient($token);
    $bot = new \LINE\LINEBot($httpClient, ['channelSecret' => 'XXXXXXXX']);

    $imageUrl = new UriTemplateActionBuilder('Prodotto', $photo);
    $buttonTemplateBuilder = new ButtonTemplateBuilder(
                       'TEST',
                       $message,
                       $photo,
                       [
                           new UriTemplateActionBuilder('BUY IT!', $url)
                       ]
                   );
    $templateMessage = new TemplateMessageBuilder('Button alt text', $buttonTemplateBuilder);
    $response = $bot->replyMessage("XXXXXXX", $templateMessage);

**Comment by kiwi-26** [comment]
Is This issue related only button template message? Or all message?

If you can't "push" ANY message and you can "reply" some messages, you might use LINE@ free account.
You can use pushMessage when you use LINE@ developer trial plan or pro(API) plan.

**Comment by cyb3rwin** [comment]
I have same issue too, this is my code

**use part**
```
use ReflectionClass;
use LINE\LINEBot;
use LINE\LINEBot\Event\MessageEvent;
use LINE\LINEBot\Event\MessageEvent\TextMessage;
use LINE\LINEBot\Event\MessageEvent\StickerMessage;
use LINE\LINEBot\Event\MessageEvent\LocationMessage;
use LINE\LINEBot\Event\MessageEvent\ImageMessage;
use LINE\LINEBot\Event\MessageEvent\AudioMessage;
use LINE\LINEBot\Event\MessageEvent\VideoMessage;
use LINE\LINEBot\Event\MessageEvent\UnknownMessage;
use LINE\LINEBot\TemplateActionBuilder\MessageTemplateActionBuilder;
use LINE\LINEBot\MessageBuilder\TextMessageBuilder;
use LINE\LINEBot\MessageBuilder\TemplateMessageBuilder;
use LINE\LINEBot\MessageBuilder\TemplateBuilder\ButtonTemplateBuilder;
```

**ReplyMessage part**
```
$btnMsgBuilder = new ButtonTemplateBuilder(
    'Judul',
    'Deskripsi', 
    'http://s5.tinypic.com/iozy4h_th.jpg',
    [
        new MessageTemplateActionBuilder('One', 'button 1'),
        new MessageTemplateActionBuilder('Two', 'button 2'),
        new MessageTemplateActionBuilder('Three', 'button 3'),
    ]
);

$templateMessage = new TemplateMessageBuilder('Button alt text', $btnMsgBuilder);
$this->bot->replyMessage($replyToken, $templateMessage);
```

I try ConfirmTemplateBuilder and work, but this ButtonTemplateBuilder did not work.
I use LINE@ developer trial plan.

**Comment by lintangtimur** [comment]
@cyb3rwin try img url in HTTPS

**Comment by cyb3rwin** [comment]
Thanks @lintangtimur it works, but if i need no image header what i'm supposed to do? I can't just give empty string inside imageurl?

**Comment by lintangtimur** [comment]
from [API reference](https://developers.line.me/en/docs/messaging-api/reference/#buttons), its optional, just try it with empty string

[ButtonTemplateBuilder source](https://github.com/line/line-bot-sdk-php/blob/master/src/LINEBot/MessageBuilder/TemplateBuilder/ButtonTemplateBuilder.php)

**Comment by marlinewijaya** [comment]
I also want the button template with no image header, I've try it with empty string, doesn't work
