### ISSUE TITLE
Support OAuth2 API

### ISSUE THREAD

**Issue by yoko-chance** [line/line-bot-sdk-php#147]
This SDK seem missing method for call some endpoint on current Messaging API.

e.g. 
`POST https://api.line.me/oauth2/v2.1/token`
`GET https://api.line.me/v2/profile`
(and httpclient in this SDK seem to does not have way for GET method with header)

Are these methods implemented in the near future?

thank you.

**Comment by Vaduz** [comment]
I'll add oauth2 api. Please hold on.

**Comment by Vaduz** [comment]
I thought that supporting OAuth2 API in this SDK has synergy to build line bots, but it's not.
LINE's social API is providing generic OAuth2 API, so it's better for users and security seasons to use well verified OAuth2 client.
