### ISSUE TITLE
how to create a new line break in message text?

### ISSUE THREAD

**Issue by asdqwe3124** [line/line-bot-sdk-php#15]
\n or \n\r not working anymore in new API.

**Comment by moznion** [comment]
Thank you for your asking.

That sounds a bit strange. Please try following example:

```php
$httpClient = new \LINE\LINEBot\HTTPClient\CurlHTTPClient('<channel access token>');
$bot = new \LINE\LINEBot($httpClient, ['channelSecret' => '<channel secret>']);
$this->echoBack($replyToken, "Hello\nWorld");
```

Probably this example replies as

```
Hello
World
```

**Comment by asdqwe3124** [comment]
still not working.
I got response: 
`{"message":"The property, 'messages[0].text', in the request body is invalid (line: 6, column: 13)"}`

**Comment by moznion** [comment]
Hmm... could you show me your code?

**Comment by asdqwe3124** [comment]
Upss sorry, it's working now..

Thanks

**Comment by clazord** [comment]
@asdqwe3124  what did you do to make it work?
