### ISSUE TITLE
Add "leaveGroup" and "leaveRoom" to Tiny SDK

### ISSUE THREAD

**Issue by supersonictw** [line/line-bot-sdk-php#163]
I think the "line-bot-sdk-tiny" should be need "leaveGroup" and "leaveRoom"
I paste my code and hope to update it ;)

    public function leaveRoom($roomId)
    {
        $header = array(
            'Authorization: Bearer ' . $this->channelAccessToken,
        );

        $context = stream_context_create(array(
            "http" => array(
                "method" => "POST",
                "header" => implode("\r\n", $header),
                "content" => "[]",
            ),
        ));

        $response = file_get_contents('https://api.line.me/v2/bot/room/'.urlencode($roomId).'/leave', false, $context);
        if (strpos($http_response_header[0], '200') === false) {
            http_response_code(500);
            error_log("Request failed: " . $response);
        }
    }

    public function leaveGroup($groupId)
    {
        $header = array(
            'Authorization: Bearer ' . $this->channelAccessToken,
        );

        $context = stream_context_create(array(
            "http" => array(
                "method" => "POST",
                "header" => implode("\r\n", $header),
                "content" => "[]",
            ),
        ));

        $response = file_get_contents('https://api.line.me/v2/bot/group/'.urlencode($groupId).'/leave', false, $context);
        if (strpos($http_response_header[0], '200') === false) {
            http_response_code(500);
            error_log("Request failed: " . $response);
        }
    }

**Comment by Vaduz** [comment]
`line-bot-sdk-tiny` is intended to express minimalistic implementation about using LINE bot API.
So we are not having a plan to implement other feature on it.
