### ISSUE TITLE
Is it possible to get group name by groupId?

### ISSUE THREAD

**Issue by zombozo12** [line/line-bot-sdk-php#173]
group name might help me to build chatbot, to store it in my database as a data.

**Comment by vocolboy** [comment]
Message API has not provided the getGroupName api.

**Comment by zombozo12** [comment]
Will any chance be provided?

**Comment by Vaduz** [comment]
I have no idea and I can't help you.
It's good to inform the idea to `line-platform-feedback` not here.
https://github.com/line/line-platform-feedback
