### ISSUE TITLE
The requested package linecorp/line-bot-sdk 3.3.0 exists as linecorp/line-bot-sdk

### ISSUE THREAD

**Issue by bayuns** [line/line-bot-sdk-php#176]
I'm check folder examples and sub folder KitchenSink, error request package 3.3.0

**$composer install**
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package linecorp/line-bot-sdk 3.3.0 exists as linecorp/line-bot-sdk[0.0.1, 0.0.2, 0.1.0, 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.4.0, 1.5.0, 1.6.0, 2.0.0, 2.1.0, 2.2.0, 2.3.0, 3.0.0, dev-master] but these are rejected by your constraint.

---------------------------------------

- PHP 7.2.8
- Composer version 1.7.2 2018-08-16 16:57:12

Any solution?

**Comment by satosby** [comment]
Please check composer config.
```
$ composer config -l|grep packagist
[repositories.packagist.org.type] composer
[repositories.packagist.org.url] https://packagist.org
```
If you are using the packagist mirror site, please try this:
```
$ composer config -g repos.packagist composer https://packagist.org
```

**Comment by bayuns** [comment]
thankyou @satosby 

happy coding :D
