### ISSUE TITLE
can i send message to all users without replyToken?

### ISSUE THREAD

**Issue by siputra12** [line/line-bot-sdk-php#178]
i want make script broadcasting and i dont know this can or not, please reply me

**Comment by kiwi-26** [comment]
If you are using PRO (API) plan, you can push message for your users.
There are no broadcast API, so you have to send message for each user.

You can also create message for all users from LINE@ manager console.

**Comment by habibimustafa** [comment]
Maybe you can use multicast message (max. 150 users in one sent)
