### ISSUE TITLE
auto reply not work

### ISSUE THREAD

**Issue by sprabowo** [line/line-bot-sdk-php#18]
i just installed kitchen sink on hosting and have configured webhook to callback. when i try to chat from phone 'profile', line bot cant reply. i just want to learn event handler especially text message

**Comment by moznion** [comment]
Is other text reaction active? If not, probably configuration or launch method is wrong.

**Comment by sprabowo** [comment]
yeah, there is no. i just configure settings in src/LINEBot/KitchenSink/Setting.php to add Token and Secret. then i configured public/index.php to edit require autoload.php then in webhook i set http://my_web_folder/public/callback. is that true? because i just saw simply route to callback

**Comment by moznion** [comment]
Please try to set `http://my_web_folder/callback` instead of `http://my_web_folder/public/callback` as a callback.

**Comment by sprabowo** [comment]
Webhook URL is not found. when i try to verify. still cant get reply. btw when i use php 5.4, webhook url got verified with PHP 5.4 but when i access http://my_web_folder/public/callback get error. when i changed php version into 5.6, http://my_web_folder/public/callback get response but i cant verify, the error is 500 internal server. any idea?

**Comment by moznion** [comment]
If request is failed on verifying phase, perhaps wrong the channel access token and channel secret. Please check it.

**Comment by sprabowo** [comment]
oke its solved.
in the /-src
we need upload LINEBot.php, then copy folder HTTPClient to/LINEBot.

so folder structure become
/-public
/-vendor
/-src
   /--LINEBot
       /---HTTPClient
   /--LINEBot.php

documentation form example is not full. so confused for beginner

**Comment by moznion** [comment]
That is strange. Did you execute `composer install`?

**Comment by sprabowo** [comment]
ye i did it. i just copy KitchenSink from example folder then i put in public html then composer install. is that wrong procedure?

**Comment by moznion** [comment]
I got it. In my estimation, the problem is simple.

You say `copy KitchenSink from example folder`; probably it broke relation of the structure between example app and SDK directory.

Now, we should keep directory tree as is git cloned because example app's composer.json doesn't have the dependency that belongs to bot SDK.

I'll add dependency to the bot SDK to composer.json of example application. It makes be fine.

**Comment by sprabowo** [comment]
oke, thanks @moznion.

**Comment by moznion** [comment]
Fixed at 1469751c136debc555fb007ee50b61270a384ee8.
