### ISSUE TITLE
Send "Alphabet Emoticons"

### ISSUE THREAD

**Issue by Wildan33** [line/line-bot-sdk-php#180]
Can I made my bot send/reply with alphabet emoticon? For example the emoticon in the image attached. 

This is actually my first time posting an issue, so I'm sorry if I made mistake. 
![emot](https://user-images.githubusercontent.com/37075300/46241114-94b65980-c3dc-11e8-8497-43e26bf3e69d.PNG)

**Comment by Wildan33** [comment]
I probably had done mistake in writing this question so that nobody answered. I'm really sorry since this is my first time asking here, but I really want to finish this simple practice project. It has been 2 weeks and I've done lots of googling or whatever it was. 

Thank you and I'm sorry.

**Comment by Vaduz** [comment]
https://developers.line.me/en/docs/messaging-api/message-types/#sticker-messages

**Comment by Vaduz** [comment]
According to the sticker list, alphabet emoticons are not supported.
