### ISSUE TITLE
Import Json to Flex Message Object

### ISSUE THREAD

**Issue by habibimustafa** [line/line-bot-sdk-php#182]
Hello, in Java SDK I can import json flex message template to `FlexMessage` object with `ObjectMapper`.
Does this also work in PHP SDK?

**Comment by Vaduz** [comment]
Unfortunately this SDK doesn't support such feature for now.
But it's make sense to me that generate Flex message on the developer console and then copy and paste JSON string to your code without using message builder.

**Comment by habibimustafa** [comment]
Oh, okay.
I hope this feature can be immediately available to make it easier when building flex messages.
