### ISSUE TITLE
PHP 5.6/7.0/7.1 EOL

### ISSUE THREAD

**Issue by Vaduz** [line/line-bot-sdk-php#193]
As you may know, PHP 5.6/7.0 will be EOL in end of 2018.
http://php.net/supported-versions.php

We are supporting PHP 5.5 that has already EOL in middle of 2016.
But if we're facing issues that blocked by PHP versions to develop a new feature, we'll discontinue to support those PHP versions.

We'll support PHP 5.5 as much as possible. Because GAE standard environment supports PHP 5.5.
Please tell me if you have other issues or considerations.

**Comment by tkgauri** [comment]
@Vaduz Can we move this information to Readme file and close this issue?

**Comment by Vaduz** [comment]
There is no place to listen to voices of users if I close this issue.
I'd like to know considerations of users until discontinue those versions.

**Comment by Vaduz** [comment]
Google Ads API Client discontinues PHP ~7.0
https://developers-jp.googleblog.com/2019/03/php-google-ads-api-php-adwords.html

**Comment by Vaduz** [comment]
WordPress will not support PHP 5.2 to 5.5.
https://core.trac.wordpress.org/changeset/44950

**Comment by Vaduz** [comment]
To continue support PHP 5.5, we fixed CI #242

**Comment by Vaduz** [comment]
GAE suports PHP 7+.
Now we can stop support PHP 5, or just PHP 5.5.
https://cloud.google.com/appengine/docs/php/?hl=en
https://cloud.google.com/appengine/docs/standard/php7/quickstart?hl=en

**Comment by Vaduz** [comment]
FYI: PHP 7.2 runtime supported by Azure and Google Cloud
- Azure (5.6, 7.0, 7.2)
https://docs.microsoft.com/en-us/azure/app-service/web-sites-php-configure
- Google Cloud (5.5, 7.2)
https://cloud.google.com/appengine/docs/standard/php7/runtime

**Comment by tokuhirom** [comment]
The PHP SDK stopped supporting  PHP 5.5.
https://github.com/line/line-bot-sdk-php/pull/309
