### ISSUE TITLE
How to get the preview of the sticker

### ISSUE THREAD

**Issue by ipol2n** [line/line-bot-sdk-php#2]
I read the callback example from 
https://github.com/line/line-bot-sdk-php/blob/master/examples/EchoBot/src/routes.php.

Could you tell me how to get the url of sticker?

Thank you in advance

**Comment by moznion** [comment]
Thank you for your asking.

In short, there is no way to realize such matter. You can only get `ID of the sticker`, `Package ID of the sticker` and `Version number of the sticker`.

Please refer to the following documentation;
https://developers.line.me/bot-api/api-reference#sending_message_sticker
