### ISSUE TITLE
Not define for '$response->isSecceeded()'

### ISSUE THREAD

**Issue by gotraveltoworld** [line/line-bot-sdk-php#20]
From example code :
`$textMessageBuilder = new \LINE\LINEBot\MessageBuilder\TextMessageBuilder('hello');`
`$response = $bot->replyMessage('<reply token>', $textMessageBuilder);`
`if ($response->isSecceeded()) {`
`echo 'Succeeded!';`
    `return;`
`}`

I want to execute example code. But php console show the error message for me.
Please check this function name exist or not.  

Thank you.

**Comment by be-hase** [comment]
Hi, @gotraveltoworld 

hmmm...It looks typo.
Please try to run `$response-> isSucceeded()`.

And we will fix README.md. 
Thanks.

When the supplementary explanation, 
`$bot->replyMessage` returns `Response` object.
https://github.com/line/line-bot-sdk-php/blob/master/src/LINEBot/Response.php#L55-L63

**Comment by moznion** [comment]
Now typo is fixed, thank you @be-hase.

Thank you for your reporting @gotraveltoworld.
