### ISSUE TITLE
CameraRollTemplateActionBuilder() is not working

### ISSUE THREAD

**Issue by o150209001** [line/line-bot-sdk-php#204]
sorry,I try use the CameraRollTemplateActionBuilder ,but my RichMenu is not happend anything.

**Comment by kiwi-26** [comment]
As written in the API reference, camera roll action can be configured only with quick reply buttons. So you can't use this action in rich menu.
https://developers.line.biz/en/reference/messaging-api/#camera-roll-action

**Comment by o150209001** [comment]
> As written in the API reference, camera roll action can be configured only with quick reply buttons. So you can't use this action in rich menu.
> https://developers.line.biz/en/reference/messaging-api/#camera-roll-action

ok ,thank you!!
