### ISSUE TITLE
Webhook event objects support status check

### ISSUE THREAD

**Issue by tkgauri** [line/line-bot-sdk-php#206]
I created this question in order to know which event types are already supported and which ones are yet to be implemented.
If a particular event is already supported by PHP bot-sdk then please tick the checkbox against it. 

https://developers.line.biz/en/reference/messaging-api/#webhook-event-objects
-  Common properties
	- [x] Source user
	- [x] Source group
	- [x] Source room
-  Message event
	- [x] Text
	- [x] Image
	- [x] Video
	- [x] Audio
	- [x] File
	- [x] Location
	- [x] Sticker
- [x] Follow event
- [x] Unfollow event
- [x] Join event
- [x] Leave event
- [x] Member join event
- [x] Member leave event
- [x] Postback event
- [x] Beacon event
- [x] Account link event
- [x] Device link event
- [x] Device unlink event

**Comment by tokuhirom** [comment]
Account Link event was supported: https://github.com/line/line-bot-sdk-php/blob/707cfae448b3a5bde44e1d360f4dc743b69c7ffd/src/LINEBot/Event/AccountLinkEvent.php
device link/unlink was supported: https://github.com/line/line-bot-sdk-php/blob/f97cf3834e91f8dea20be733a5a812dc1d5305a8/src/LINEBot/Event/ThingsEvent.php
