### ISSUE TITLE
グループチャット時のメッセージイベントについて

### ISSUE THREAD

**Issue by Ma510** [line/line-bot-sdk-php#22]
はじめまして。

グループチャット時は、
受け取ったメッセージイベントのソースに、ルーム情報が入りますが、
合わせて、ユーザー情報（IDなど）を知る方法はないでしょうか？

よろしくお願いします。

**Comment by moznion** [comment]
ご質問ありがとうございます．

グループチャット時にそのグループに所属しているユーザ情報を取得することは現時点では不可能となっております．申し訳ございません．

よろしくお願いします．

--

Thank you for your asking.
Now, it cannot to retrieve information of the member of the group on group chat.
Thank you.

**Comment by Ma510** [comment]
早速の返信、ありがとうございます！
返信内容、承知しました。

ちなみに、そのグループに所属しているユーザーの取得ではなく、
そのメッセージが、どのユーザーからで、さらに、どのルームからなのか、
を知りたかった、という意味でした。
同じく現時点では不可能かと思いますが、念のため。

**Comment by moznion** [comment]
同様に不可能となっております．申し訳ございません．
よろしくお願いします．

**Comment by Ma510** [comment]
承知しました。
ありがとうございました。
