### ISSUE TITLE
add flex message and confirm message

### ISSUE THREAD

**Issue by Dimasilham7** [line/line-bot-sdk-php#226]
i want my chatbot was replying flex message and confirm message at the same time, i was trying but it can't works, can someone give me some example maybe ? thanks

**Comment by tokuhirom** [comment]
what do you want to do?  I can't understand what you want. Could you describe more details?

**Comment by Dimasilham7** [comment]
i want my bot reply my message flex message and confirm message at the same time, mean when i use some keywords this 2 (flex and confirm) come up at the same time

**Comment by Dimasilham7** [comment]
![42355](https://user-images.githubusercontent.com/31701216/58079331-f67d3b00-7bda-11e9-818a-c6f2dc3e3eee.jpg)

i mean like this on the pict

**Comment by Dimasilham7** [comment]
BTW im using PHP

**Comment by whchi** [comment]
Hi, @Dimasilham7
You can checkout my source code to see how I implement method ‘reply’.
link: https://github.com/whchi/laravel-linebot-wrapper/blob/master/src/Traits/MessageReplier.php

**Comment by habibimustafa** [comment]
Hi @Dimasilham7 
Maybe you can try to use MultiMessage Builder
```
// flex message
$flexTemplate = file_get_contents("flex_message.json");
$flexMessageBuilder = new RawMessageBuilder([
    'type' => 'flex',
    'altText' => 'Test Flex Message',
    'contents' => json_decode($flexTemplate)
]);

// confirm message
$actionBuilders = new MessageTemplateActionBuilder(...);
$confirmMessageBuilder = new ConfirmTemplateBuilder(
    'Ada lagi yang bisa Vero bantu?',
    $actionBuilders
);

 
// multi message
$multiMessageBuilder = new MultiMessageBuilder();
$multiMessageBuilder->add($flexMessageBuilder);
$multiMessageBuilder->add($confirmMessageBuilder);
 
// send
$bot->replyMessage($replyToken, $multiMessageBuilder);
```

**Comment by Dimasilham7** [comment]
thankyou guys, case close
