### ISSUE TITLE
parseEventRequest return

### ISSUE THREAD

**Issue by Kyrozyn** [line/line-bot-sdk-php#228]
in ver 3.9.0 and above the parseEventRequest function no longer return the LINE\LINEBot\Event\BaseEvent object and return mixed object?
it's difficult for me to use code completion. is there any solution?
ex code : 
ver < 3.9.0
```
$events = $bot->parseEventRequest($req->getBody(), $signature[0]);
//events is a BaseEvent[]
    foreach ($events as $event) {
        //event is a BaseEvent
    }
```
ver >= 3.9.0
```
$events = $bot->parseEventRequest($req->getBody(), $signature[0]);
//events is a mixed?
    foreach ($events as $event) {
        //event is a mixed?
    }
```

**Comment by moririnson** [comment]
@Kyrozyn BaseEvent[] should be returned unless you pass false as the third argument (`$eventOnly`) of `LINE\LINEBot@parseEventRequest`.
if you pass false, return array of string and $events（BaseEvent[]）
Are you in trouble with something?
