### ISSUE TITLE
Get user ID from group chat message

### ISSUE THREAD

**Issue by timgshi** [line/line-bot-sdk-php#25]
When receiving a message from a room, only the room ID is given as the source of the message. How do I look up the user ID of the sender?

**Comment by tokuhirom** [comment]
Duplicated https://github.com/line/line-bot-sdk-java/issues/40

**Comment by kelvinhalim13** [comment]
I hope we could get each user_id in group chat or room chat, because i need that for reply message by each user in room. I need this because i want to trying to make a simple 'room game' from my BOT
