### ISSUE TITLE
Support stay event added to beacon event

### ISSUE THREAD

**Issue by tkgauri** [line/line-bot-sdk-php#258]
> In the Messaging API beacon event, a stay event has been added to indicate that the user is staying in the covered area of the beacon.

Messaging api reference: https://developers.line.biz/en/reference/messaging-api/#beacon-event
News: https://developers.line.biz/en/news/#a-stay-event-was-added-to-beacon-event-2019-12-06

**Comment by moririnson** [comment]
We may not need to do anything.
Because there is no constant class that represents the type of beacon event, it should work without any problems with the existing implementation.

https://github.com/line/line-bot-sdk-php/blob/master/tests/LINEBot/EventRequestParserTest.php#L687

**Comment by Vaduz** [comment]
Thank you for confirmation.
