### ISSUE TITLE
$response has no 'getBody' method when push message

### ISSUE THREAD

**Issue by catwithlover** [line/line-bot-sdk-php#26]
There is a slight error in API Reference ( [https://devdocs.line.me/en/?php#reply-message]("Push Message" section) ):

```
$httpClient = new \LINE\LINEBot\HTTPClient\CurlHTTPClient('<channel access token>');
$bot = new \LINE\LINEBot($httpClient, ['channelSecret' => '<channel secret>']);

$textMessageBuilder = new \LINE\LINEBot\MessageBuilder\TextMessageBuilder('hello');
$response = $bot->pushMessage('<to>', $textMessageBuilder);

echo $response->getHTTPStatus() . ' ' . $response->getBody();
```

After I tried this code, i got error message say $response has no 'getBody' method,
I think we should call 'getRawBody' method, not 'getBody'.

**Comment by moznion** [comment]
Thank you for your reporting.
Right, that is typo. We will fix them.
Thank you.

**Comment by moznion** [comment]
These typos are fixed now. Thank you for your reporting.
