### ISSUE TITLE
Help needed!

### ISSUE THREAD

**Issue by startech-dev** [line/line-bot-sdk-php#265]
Hi, Just need help around these two!
First, when user inputs some text, our bot needs to reply immediately with guide text.("Your request is being processed... " like this)
After server got result ,the result should come after this.
Right now, if we send first guide text, the later result text not coming.
If we block first guide text, the result message is coming.
But we need both.

Second, we need to send html formatted text, that's like bold font, and etc. (<b>Fakta</b>, like this)

**Comment by Vaduz** [comment]
You can use replyToken only **1 time**.
So your second message is going to be invalid token.

For mark up your message, consider to use Flex Message.
https://developers.line.biz/en/docs/messaging-api/using-flex-messages/
