### ISSUE TITLE
Get language in Line app

### ISSUE THREAD

**Issue by manhdd-1633** [line/line-bot-sdk-php#266]
How can I get the language of the user setting in their Line App ?
I am trying to use line messaging api to build some bots.
How to retrieve the user locale from user profiles?

I don't see any api definition in the documents. Does it even supported? or default is English?

**Comment by tkgauri** [comment]
@manhdd-1633 
Unfortunately, this feature is not supported as of now. We will take note of this feedback while adding new features to Messaging-api. Thank you.

**Comment by moririnson** [comment]
@manhdd-1633 the feature was released at 4/14.
We will add it with #281, so please wait for a while.
