### ISSUE TITLE
How to find the group ID

### ISSUE THREAD

**Issue by kiennatibula** [line/line-bot-sdk-php#272]
Hi, Good day. I would like to ask how to get a group ID. I already in the group. Because I will use it  in push message API to send a message in my group .

**Comment by moririnson** [comment]
@kiennatibula see this.
https://developers.line.biz/ja/reference/messaging-api/#webhook-event-objects
you can get group id from source prop.

**Comment by moririnson** [comment]
@kiennatibula Are you okay? I will close this issue, so if you have any other questions, please create as new.

**Comment by kiennatibula** [comment]
I already solved it, thanks
