### ISSUE TITLE
[Bug Report] TextMessageBuilder might skip its attributes with null attribute

### ISSUE THREAD

**Issue by snmatsui** [line/line-bot-sdk-php#277]
## Bug Report

**Describe the bug**
TextBuilder constructor receives attiributes like extraTexts, QuickReply etc.
Considering that dynamical usage like:
```
new TextBuilder($mainText, $appendixText, $quickReply);
```
When the case that appendixText is unnecessary, the constructor might be:
```
new TextBuilder("foo", null, $quickReply);
```
However, this TextBuilder built results is:
```
{"type":"text","text":"foo"}
```

If second attribute is null, The builder skips other attributes.

https://github.com/line/line-bot-sdk-php/blob/master/src/LINEBot/MessageBuilder/TextMessageBuilder.php#L59-L80

**Comment by moririnson** [comment]
@snmatsui If the second argument of the TextBuilder constructor is null, the message is included only when it is not null.
If you know that null can be included in the second argument in the first place, first of all, if you know it can include null, I think you should pass `quickReply` to the second argument. What do you think?

**Comment by moririnson** [comment]
@snmatsui thanks.
If the second argument of the TextBuilder constructor is null, the message is ignore arguments after it.
If you know that null can be included in the second argument in the first place, first of all, if you know it can include null, I think you should pass `quickReply` to the second argument. What do you think?

**Comment by moririnson** [comment]
are you ok?
i'll close this issue. if you have any questions, please create as new issue.

**Comment by snmatsui** [comment]
I am sorry for the delay in my response, 
I rethink this problem,We should pass paramaters without null because $appendixText is mixed content. so it should be treated carefully
