### ISSUE TITLE
How to send more than one reply?

### ISSUE THREAD

**Issue by YuK1Game** [line/line-bot-sdk-php#28]
Document reply-message in https://devdocs.line.me/ja/#reply-message
"**Message to be sent Up to 5**"

How to use '\LINEBot\replyMessage' multiple messages?

**Comment by tokuhirom** [comment]
If you want 6+ messages, you need to use push message*.

**Comment by YuK1Game** [comment]
thanks!
but i find a 'LINE\LINEBot\MessageBuilderMultiMessageBuilder'

**Comment by moznion** [comment]
Yes, you can use LINE\LINEBot\MessageBuilder\MultiMessageBuilder to build multiple messages. This builder constructs a message payload (it means `array of send message objects`) that contains multiple messages.

**Comment by moznion** [comment]
Sorry, that is undocumented function so it is not friendly for developers.
I will write the sample code about sending multiple messages.

**Comment by zelief** [comment]
so @moznion where is the sample code ? iam using line-bot-sdk-tiny

**Comment by Naufal-FR** [comment]
@zelief To send multiple messages you can add new array inside of messages array content. 
Using the tiny version, it will looks like this ;

![image](https://cloud.githubusercontent.com/assets/24642717/24105242/d0ec02fc-0db6-11e7-9802-3f370e624afc.png)

You can do this up to 5 array, just be sure to add `,` at the end of each array except for the last one.

**Comment by zelief** [comment]
thanks @Naufal-FR i will try it

**Comment by sandmanzz** [comment]
![image](https://cloud.githubusercontent.com/assets/21254367/24330574/1a04835e-124b-11e7-9a95-7e992cb73e86.png)

and i got

![image](https://cloud.githubusercontent.com/assets/21254367/24330579/3b9a895a-124b-11e7-95bb-54688ea57bac.png)

**Comment by Naufal-FR** [comment]
@sandmanzz Are you using the full blown API or only the Tiny Version of it ?

**Comment by sandmanzz** [comment]
use Tiny Version @Naufal-FR

**Comment by moznion** [comment]
Please don't discuss on unrelated issue thread. This issue has been closed.
