### ISSUE TITLE
Messaging API - May 2020 update

### ISSUE THREAD

**Issue by tkgauri** [line/line-bot-sdk-php#284]
News: https://developers.line.biz/en/news/2020/05/12/messaging-api-update-may-2020/

- [ ] Message character limit and media file usage conditions changed
- [ ] [Get LINE emoji information from the text object of a webhook event](https://developers.line.biz/en/reference/messaging-api/#wh-text)
- [ ] [Retry failed message](https://developers.line.biz/en/reference/messaging-api/#retry-api-request)

**Comment by moririnson** [comment]
>  Message character limit and media file usage conditions changed

no need to action

> Get LINE emoji information from the text object of a webhook event

* https://github.com/line/line-bot-sdk-php/pull/287

>  Retry failed message

* https://github.com/line/line-bot-sdk-php/pull/288
