### ISSUE TITLE
[Bug Report] ButtonTemplateBuilder title ignores "0"

### ISSUE THREAD

**Issue by snmatsui** [line/line-bot-sdk-php#285]
## Bug Report

**Describe the bug**
We cannot make ButtonTemplate which title is "0".

**To Reproduce**
1. instantiate ButtonTemplateBuilder like:
```
$builder = new ButtonTemplateBuilder("0", "buttonText");
```
2. `$builder->buildTemplate` returns without title

**Expected behavior**
it may return with title "0"

**Environment (please complete the following information):**
 - OS: AmazonLinux2
 - PHP version  7.1.33
 - line-bot-sdk-php version 4.3.0

**Comment by Vaduz** [comment]
Confirmed current code doesn't handle "0" properly.
