### ISSUE TITLE
Kitchensink just echo's back what i say

### ISSUE THREAD

**Issue by gdtesam** [line/line-bot-sdk-php#292]
I've been using the tinybot for a while so thought i'd try to expand and use the kitchensink.
It all seems to be working but all it does is echo back what i say.

**Comment by gdtesam** [comment]
nevermind i see it's case sensitive now, anyway to make it recognise both or would i have to make 2 cases?

**Comment by Vaduz** [comment]
Yes. If you want to change it, [strtolower ](https://www.php.net/manual/en/function.strtolower.php) the `$text` [here](https://github.com/line/line-bot-sdk-php/blob/master/examples/KitchenSink/src/LINEBot/KitchenSink/EventHandler/MessageHandler/TextMessageHandler.php#L89).

**Comment by gdtesam** [comment]
thank you for the help
