### ISSUE TITLE
Kitchensink sample code partially working.

### ISSUE THREAD

**Issue by gdtesam** [line/line-bot-sdk-php#294]
Hi i'm using the Kitchen sink and just working my way through it getting my head around it.
I'm familiar with php but no expert, i've been using tinybot for a while and i'm trying to get to grips with some of the other possibilities.
My issue i'm having is anything past the 'imagemap' case doesn't work in the sample code. I've tried cloning the repo, downloading the zip and updating via composer.
![Screenshot_20200626_114135](https://user-images.githubusercontent.com/21229905/85848954-fff3b200-b7a1-11ea-9efb-6ac6845fb6bc.jpg)
I don't get any error logs relating to this.
Any thoughts?

**Comment by moririnson** [comment]
thanks.
looks to me the imagemap in your screenshot is working. Can you explain what you expect and what doesn't work for detail?

**Comment by gdtesam** [comment]
In the sample code provided I can get a response from everything but those below imagemap.

Imagemapvideo, Restaurant, shopping and quickReply do not give me a response.
I'd really like to use the flex message mainly.

**Comment by moririnson** [comment]
@gdtesam 
first of all, some your specific text are wrong, check it. ex. Imagemapvideo → imagemapVideo
second, did you read this sentences?
https://github.com/line/line-bot-sdk-php/blob/master/examples/KitchenSink/README.md#notes

**Comment by gdtesam** [comment]
When i created this post I had used this on the $text so i didn't need to worry about it being case sensitive. 
`$text = strtolower($this->textMessage->getText());`
With or without this makes no difference.
I've read all those sentences more than twice and i don't see any issues related to any of that or other things wouldn't work like carousel or imagemap.

**Comment by moririnson** [comment]
ok. 

> I don't get any error logs relating to this.

can you challenge this code?（if you use php >= 7）

```
            case 'imagemapVideo':
                try {
                    // image map video send implementations
                } catch (\Exception $e) {
                    $this->echoBack($replyToken, 'status:' . $e->getMessage());
                }
```

**Comment by gdtesam** [comment]
before i tried this i copied the new release files 4.5.0 and that has solved the issue, i have no idea what the problem was but i'd like to thank you for replying to me. Hopefully i won't need to ask anymore questions.
