### ISSUE TITLE
Messaging API - August 2020 update

### ISSUE THREAD

**Issue by tkgauri** [line/line-bot-sdk-php#297]
News: https://developers.line.biz/en/news/2020/08/04/messaging-api-update-august-2020/

- [ ] [Unsend event has been added](https://developers.line.biz/en/reference/messaging-api/#unsend-event)
- [ ] [Video viewing complete event has been added](https://developers.line.biz/en/reference/messaging-api/#video-viewing-complete)
- [ ] [The audiences property is now optional instead of required for a certain endpoint](https://developers.line.biz/en/reference/messaging-api/#create-upload-audience-group)
- [ ] [Create audience for uploading user IDs (by file)](https://developers.line.biz/en/reference/messaging-api/#create-upload-audience-group-by-file)
- [ ] [Add user IDs or Identifiers for Advertisers (IFAs) to an audience for uploading user IDs (by file](https://developers.line.biz/en/reference/messaging-api/#update-upload-audience-group-by-file)

**Comment by moririnson** [comment]
supported by https://github.com/line/line-bot-sdk-php/releases/tag/4.6.0
