### ISSUE TITLE
FlexMessageBuilder not work, cannot setSender how to set and send?

### ISSUE THREAD

**Issue by boyphongsakorn** [line/line-bot-sdk-php#304]
`$textMessageBuilder = new \LINE\LINEBot\MessageBuilder\FlexMessageBuilder('camera',json_decode($wow, true),'none','X72x3xxx18xxxx33442x1x1xx3x0x1370');`

after run i get this error

_Fatal error: Uncaught TypeError: Argument 3 passed to LINE\LINEBot\MessageBuilder\FlexMessageBuilder::__construct() must be an instance of LINE\LINEBot\QuickReplyBuilder or null, string given, called in /home/pwisetthon/domains/pwisetthon.com/public_html/teamquadb/xcs_result.php on line 72 and defined in /home/pwisetthon/domains/pwisetthon.com/public_html/teamquadb/vendor/linecorp/line-bot-sdk/src/LINEBot/MessageBuilder/FlexMessageBuilder.php:57 Stack trace: #0 /home/pwisetthon/domains/pwisetthon.com/public_html/teamquadb/xcs_result.php(72): LINE\LINEBot\MessageBuilder\FlexMessageBuilder->__construct('\xE0\xB9\x82\xE0\xB8\xAD\xE0\xB8\x99\xE0\xB8\x84\xE0\xB9\x88...', Array, 'none', 'X72x3xxx18xxxx3...') #1 {main} thrown in /home/pwisetthon/domains/pwisetthon.com/public_html/teamquadb/vendor/linecorp/line-bot-sdk/src/LINEBot/MessageBuilder/FlexMessageBuilder.php on line 57_

**Comment by moririnson** [comment]
Sorry to your inconvenience.
this problem has been resolved v4.4.2 or later.
