### ISSUE TITLE
Reply using image?

### ISSUE THREAD

**Issue by mokalovesoulmate** [line/line-bot-sdk-php#307]
Hello, I was able to reply by text with examples from `EchoBot/Route.php`. However, it only provide text.

I read [https://developers.line.biz/en/reference/messaging-api/#image-message](https://developers.line.biz/en/reference/messaging-api/#image-message), it uses JSON data but not sure where to put that.

Thanks!

**Comment by Vaduz** [comment]
You are using echo bot. It just reply your text message as you send.
I suggest you try to use [KitchenSink](https://github.com/line/line-bot-sdk-php/tree/master/examples/KitchenSink) example for the next step understanding this SDK.
