### ISSUE TITLE
[Feature Request] Create new package for Laravel

### ISSUE THREAD

**Issue by kawax** [line/line-bot-sdk-php#312]
I want to make this SDK compatible with Laravel.
However, support policies do not match.
I suggest creating a separate package.
`line-bot-sdk-laravel`
New SDK contains this SDK.
New SDK follows Laravel's support policy.
https://laravel.com/docs/8.x/releases

**Comment by Vaduz** [comment]
This SDK doesn't bother Laravel framework if you use proper PHP version that satisfy both of them.
Let me consider how do I improve integration with Laravel .

**Comment by kawax** [comment]
That's not enough for a Laravel-like development experience.
I'll submit some PR later.
