### ISSUE TITLE
Richmenu does not open on Android when link to user again

### ISSUE THREAD

**Issue by mvn-hungnguyen-dn** [line/line-bot-sdk-php#335]
## Bug Report

**Describe the bug**
Richmenu does not open when link again on android

**To Reproduce**
1. Link a richmenu to user -> Richmenu has open automatically
2. Unlink a richmenu from this user
3. Link a richmenu again

**Expected behavior**
Richmenu has open automatically

**Actual behavior**
Richmenu just displayed on Chat bar, not open
It's does not happened on iOS

**Environment (please complete the following information):**
 - OS: Ubuntu [16.04]
 - PHP version  [7.3]
 - line-bot-sdk-php version [6.1]

**Comment by tokuhirom** [comment]
It's not an SDK's issue. It's an API side issue.
