### ISSUE TITLE
[Bug Report]the structure of message object is not same as one of request body

### ISSUE THREAD

**Issue by gakisan8273** [line/line-bot-sdk-php#336]
## Bug Report

**Describe the bug**
There has difference of structure between `message event object` and `request body`.

**To Reproduce**
1. take a message event by webhook.
2. compare a result of request body and one of `LINE\LINEBot::parseEventRequest()`.

```php
$requestBody = $request->getContent();
$parsedEvents = $this->lineBot->parseEventRequest($requestBody, $request->header(HTTPHeader::LINE_SIGNATURE), false);
$encodedParsedEvents = json_encode(array_combine(['destination', 'events'], $events);
```

```
// $requestBody
{
  "destination":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  "events": [
    {
      "message":{"type":"text","id":"xxxxxxxxxxxxxx","text":"test"}
      "type":"message",
      "replyToken":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
      "source":{"userId":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx","type":"user"},
      "timestamp":xxxxxxxxxxxxxxxx,
      "mode":"active",
    }
  ],
}
```

```
// $encodedParsedEvents
{
  "destination":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "events": [
    {
      "message":{"type":"text","id":"xxxxxxxxxxxxxx","text":"\u3042"},  // duplicate
      "event": {                                                        // this key is not exist in request body
        "message":{"type":"text","id":"xxxxxxxxxxxxxx","text":"\u3042"} // duplicate
        "type":"message",
        "replyToken":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "source":{"userId":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx","type":"user"},
        "timestamp":xxxxxxxxxxxxxxxx,
        "mode":"active",
      }
    }
  ]
}
```

**Expected behavior**
I think the two should have same structure.
when `$encodedParsedEvents`(with signature) was stored a queue, and dequeue from other application,
it can't be parsed using `parseEventRequest()` due to invalid signature.

**Environment (please complete the following information):**
 - OS: [Alpine 9.2.0]
 - PHP version  [7.4.13]
 - line-bot-sdk-php version [6.0.0]

**Comment by hinoguma** [comment]
In my opinion, this is not bug.
ParseEventRequest() intentionally changes request_body into array of Event Class for data handling in object-oriented.

**Comment by Vaduz** [comment]
It's natural that class structures are different from json's.

**Comment by gakisan8273** [comment]
Thank you for your response.
I think it's more useful `parse json into object -> object encode into json -> re-parse json into object`  can be.
But understood that between request body and object can be  difference.

**Comment by Vaduz** [comment]
Please use json string for serialization.
