### ISSUE TITLE
leaveRoom() and leaveGroup() didn't work

### ISSUE THREAD

**Issue by readper** [line/line-bot-sdk-php#35]
got 411 bad request from server.
add request body can fix the problem.

[LINEBot.php:137](https://github.com/line/line-bot-sdk-php/blob/master/src/LINEBot.php#L137)
`return $this->httpClient->post($this->endpointBase . '/v2/bot/group/' . urlencode($groupId) . '/leave', ["dummy"=>"dummy"]);`

[LINEBot.php:148](https://github.com/line/line-bot-sdk-php/blob/master/src/LINEBot.php#L148)
`return $this->httpClient->post($this->endpointBase . '/v2/bot/room/' . urlencode($roomId) . '/leave', ["dummy"=>"dummy"]);`

**Comment by moznion** [comment]
Thank you for your reporting. However I couldn't reproduce that symptoms.
Could you show us more details (situation, usage and etc.)?

**Comment by readper** [comment]
Log for the error respond
LINE\LINEBot\Response::__set_state(array(
   'httpStatus' => 411,
   'body' => '<HTML><HEAD>
<TITLE>Bad Request</TITLE>
</HEAD><BODY>
<H1>Bad Request</H1>
Your browser sent a request that this server could not understand.<P>
Reference&#32;&#35;7&#46;2e7145cb&#46;1479391184&#46;1dc0bf2c
</BODY>
</HTML>
',
   'headers' => 
  array (
    'Server' => 'AkamaiGHost',
    'Mime-Version' => '1.0',
    'Content-Type' => 'text/html',
    'Content-Length' => '223',
    'Expires' => 'Thu, 17 Nov 2016 13:59:44 GMT',
    'Cache-Control' => 'max-age=0, no-cache, no-store',
    'Pragma' => 'no-cache',
    'Date' => 'Thu, 17 Nov 2016 13:59:44 GMT',
    'Connection' => 'close',
  ),
))

**Comment by kazuki-ma** [comment]
(update markup of @readper 's comment)

**Comment by moznion** [comment]
@readper 
The latest version 1.2.1 fixes this problem. Thank you for your reporting.
