### ISSUE TITLE
setDefaultRichMenuId doesn't work

### ISSUE THREAD

**Issue by ttaku** [line/line-bot-sdk-php#351]
## Bug Report

**Describe the bug**
When I use setDefaultRIchMenuId, the error below occurred.
```
LINE\LINEBot\Exception\CurlExecutionException
HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)
```

**To Reproduce**
Every time.

**Expected behavior**
Return correct response. LINEBot\Response 

**Environment (please complete the following information):**
 - OS: [Debian 10.6]
 - PHP version  [8.0.0]
 - line-bot-sdk-php version [7.0.0]

**Comment by tokuhirom** [comment]
It may depend on your network, OS, or PHP environment. It does not depend on the SDK method.
