### ISSUE TITLE
Support Rich menu aliases Rich menu switch action apis

### ISSUE THREAD

**Issue by tkgauri** [line/line-bot-sdk-php#356]
News: https://developers.line.biz/en/news/2021/06/21/switch-between-multiple-rich-menus/

**Comment by sor4chi** [comment]
@moririnson 
Have you already added a richmenu switch action?
I can't find `"type": "richmenuswitch"` in Constant/ActionType, which is used to implement a rich menu with switching functionality. 

https://developers.line.biz/en/reference/messaging-api/#richmenu-switch-action
