### ISSUE TITLE
[Bug Report] Undefined index: imageSet

### ISSUE THREAD

**Issue by love99067333** [line/line-bot-sdk-php#366]
## Bug Report
i upgrade linecorp/line-bot-sdk from 3.10.0 to 7.2
then i test webhook image event then 
ErrorException: Undefined index: imageSet in /vendor/linecorp/line-bot-sdk/src/LINEBot/Event/MessageEvent/ImageMessage.php:45

**Describe the bug**
i upgrade linecorp/line-bot-sdk from 3.10.0 to 7.2
then i test webhook image event then i got Error message like as mentioned above
i look up line docs:
https://developers.line.biz/en/reference/messaging-api/#wh-image
seems like imageSet just exist when users sent multi images to line OA
then i select multi images to send ,seems ok from that
is it a bug right?

**Comment by moririnson** [comment]
@love99067333 Thank for your report~
I'll check it, could you share me followings? 
* Codes thrown exception
* Webhook request payload from LINE Messaging API

**Comment by love99067333** [comment]
1.
i don't find any other exception besides
ErrorException: Undefined index: imageSet in /vendor/linecorp/line-bot-sdk/src/LINEBot/Event/MessageEvent/ImageMessage.php:45
2.
send one image to LINE OA
events: "{\"destination\":\"U46dcac1ac5d2b60e5df0b17f723fa5d3\",\"events\":[{\"type\":\"message\",\"message\":{\"type\":\"image\",\"id\":\"15103442717663\",\"contentProvider\":{\"type\":\"line\"}},\"timestamp\":1637219233484,\"source\":{\"type\":\"user\",\"userId\":\"Ubc0fb23b9635894b3d0dd406b174b3d3\"},\"replyToken\":\"85d7af82349a4ae5bfdb8371e6fc4c63\",\"mode\":\"active\"}]}"  

send multi images to LINE OA

(1 
events: "{\"destination\":\"U46dcac1ac5d2b60e5df0b17f723fa5d3\",\"events\":[{\"type\":\"message\",\"message\":{\"type\":\"image\",\"id\":\"15103458507683\",\"contentProvider\":{\"type\":\"line\"},\"imageSet\":{\"id\":\"43DBC3C0C50B4ED269FC76CAD1B693300E8C395B8B9820A724E276B0AC088C2D\",\"index\":1,\"total\":2}},\"timestamp\":1637219452357,\"source\":{\"type\":\"user\",\"userId\":\"Ubc0fb23b9635894b3d0dd406b174b3d3\"},\"replyToken\":\"3e284c0bd88a44b49a69ed0dafccf0ee\",\"mode\":\"active\"},{\"type\":\"message\",\"message\":{\"type\":\"image\",\"id\":\"15103458535552\",\"contentProvider\":{\"type\":\"line\"},\"imageSet\":{\"id\":\"43DBC3C0C50B4ED269FC76CAD1B693300E8C395B8B9820A724E276B0AC088C2D\",\"index\":2,\"total\":2}},\"timestamp\":1637219452687,\"source\":{\"type\":\"user\",\"userId\":\"Ubc0fb23b9635894b3d0dd406b174b3d3\"},\"replyToken\":\"d142b0f4d1114572a4265212cfb1a360\",\"mode\":\"active\"}]}"  
(2
 events: "{\"destination\":\"U46dcac1ac5d2b60e5df0b17f723fa5d3\",\"events\":[{\"type\":\"message\",\"message\":{\"type\":\"image\",\"id\":\"15103461161964\",\"contentProvider\":{\"type\":\"line\"},\"imageSet\":{\"id\":\"9794AA257CF5031CC5B12CD2932304CF85387053A60204FAF33B9142EDC2E641\",\"index\":2,\"total\":3}},\"timestamp\":1637219489361,\"source\":{\"type\":\"user\",\"userId\":\"Ubc0fb23b9635894b3d0dd406b174b3d3\"},\"replyToken\":\"8032312660914df8a326b9b8e1296439\",\"mode\":\"active\"},{\"type\":\"message\",\"message\":{\"type\":\"image\",\"id\":\"15103461129568\",\"contentProvider\":{\"type\":\"line\"},\"imageSet\":{\"id\":\"9794AA257CF5031CC5B12CD2932304CF85387053A60204FAF33B9142EDC2E641\",\"index\":1,\"total\":3}},\"timestamp\":1637219488901,\"source\":{\"type\":\"user\",\"userId\":\"Ubc0fb23b9635894b3d0dd406b174b3d3\"},\"replyToken\":\"7508a46c586d4a1ab05dde8d3d6ec764\",\"mode\":\"active\"}]}"  
(3
events: "{\"destination\":\"U46dcac1ac5d2b60e5df0b17f723fa5d3\",\"events\":[{\"type\":\"message\",\"message\":{\"type\":\"image\",\"id\":\"15103461191897\",\"contentProvider\":{\"type\":\"line\"},\"imageSet\":{\"id\":\"9794AA257CF5031CC5B12CD2932304CF85387053A60204FAF33B9142EDC2E641\",\"index\":3,\"total\":3}},\"timestamp\":1637219489854,\"source\":{\"type\":\"user\",\"userId\":\"Ubc0fb23b9635894b3d0dd406b174b3d3\"},\"replyToken\":\"f1068cff217e4ab3b252ced4054f1755\",\"mode\":\"active\"}]}"

**Comment by moririnson** [comment]
@love99067333 thanks. this case is bug...
We'll fixes it in near future~
