### ISSUE TITLE
Confirm template has location button is not working

### ISSUE THREAD

**Issue by thesea2201** [line/line-bot-sdk-php#376]
`Confirm` template not working when action button is 1 of 3 action objects `[location, camera, cameraRoll]`(see attached image)
`[location, camera, cameraRoll]` still work fine in `button template`. So, could you please tell me this is a bug or any suggests for this case. Thanks!

**To Reproduce**
Build a confirm template has 2 buttons: left button is location action, right button is camera action

**Expected behavior**
See a confirm template with 2 buttons are location and camera

**Screenshots**
![markup_7596 (2)](https://user-images.githubusercontent.com/21289697/165497492-1c047556-e386-420b-b4b9-0890a8a2c75b.png)

**Environment:**
 - OS: [Ubuntu]
 - PHP version [7.4.26]
 - line-bot-sdk-php version [3.15.0]

**Comment by moririnson** [comment]
@thesea2201 Could you share me your implementations?

**Comment by moririnson** [comment]
@thesea2201 Please ask us if you have anything.
Or you can post your question to this.
https://www.line-community.me/ja/questions
