### ISSUE TITLE
Images not shown properly in chat window

### ISSUE THREAD

**Issue by nevrending** [line/line-bot-sdk-php#39]
Image message sent successfully (200 OK) but image is not displayed properly in chat window

```
203.104.146.152 - - [20/Nov/2016:13:28:16 +0700] "POST /callback/line/official HTTP/1.1" 200 12 "-" "LineBotWebhook/1.0"
203.104.146.152 - - [20/Nov/2016:13:28:21 +0700] "POST /callback/line/official HTTP/1.1" 200 12 "-" "LineBotWebhook/1.0"
203.104.146.152 - - [20/Nov/2016:13:28:24 +0700] "POST /callback/line/official HTTP/1.1" 200 12 "-" "LineBotWebhook/1.0"
203.104.146.152 - - [20/Nov/2016:13:31:39 +0700] "POST /callback/line/official HTTP/1.1" 200 12 "-" "LineBotWebhook/1.0"
203.104.146.152 - - [20/Nov/2016:13:34:57 +0700] "POST /callback/line/official HTTP/1.1" 200 12 "-" "LineBotWebhook/1.0"
```

![screen shot 2016-11-20 at 13 44 40](https://cloud.githubusercontent.com/assets/4745298/20461018/839bb918-af27-11e6-8a53-f80c07d51be2.png)

- Image URL is correct and can be opened from browser
```https://line.yefta.com/images/baka.jpg```
- SSL cert is not the ones from Let's encrypt nor Cloudflare
- Images can be displayed properly if running the code using local php (php -S) and ngrok

![screen shot 2016-11-20 at 13 47 12](https://cloud.githubusercontent.com/assets/4745298/20461028/dccbeddc-af27-11e6-97a8-82461fe161cd.png)

**Comment by sprabowo** [comment]
you must give different file for _ImageMessageHandler_ between **originalContentUrl** and
**previewImageUrl**. previewImageUrl must have ratio 1:1. in kitchensink example, originalContentUrl have the same file with previewImageUrl so image cant be load.

**Comment by taufansatrio** [comment]
Hello, I'm currently having a similar problem although I'm using different Url for **originalContentUrl** and **previewImageUrl**. Is there any other possible cause? 

Thanks in advance

**Comment by sprabowo** [comment]
@taufansatrio maybe you must completed read the docs here https://devdocs.line.me/en/#send-message-object for the spesification of image

**Comment by taufansatrio** [comment]
@sprabowo I've read that and ensured the images fulfill the specification. Just tried changing the URLs to Dropbox's public link with same image and they load just fine. SSL cert/HTTPS issue perhaps?

**Comment by sprabowo** [comment]
@taufansatrio yeah i think about https. i use free ssl from letsencrypt and running well.

**Comment by nevrending** [comment]
I'm closing this as apparently I'm the only one who cannot see the images. Lol
Friends said that the images loads just fine on their Line client.
