### ISSUE TITLE
Multiplemessage disregard content after Imagemap

### ISSUE THREAD

**Issue by IronLady** [line/line-bot-sdk-php#43]
Hi, 

I am able to send a MultiMessage with a text followed by an Imagemap.
But, when I try to send an Imagemap and followed by a text. I got only the Imagemap and the text never showed up. 

Did I missed something?

**Comment by moznion** [comment]
Thank you for your asking.
Could you show us your code?

**Comment by IronLady** [comment]
Thanks for your reply

```php
$message = new MultiMessageBuilder();

// get imagemap params here as a $response

$richMessageUrl = $response['base_url'];
$imagemapMessageBuilder = new ImagemapMessageBuilder(
    $richMessageUrl,
    $response['alt_text'],
    new BaseSizeBuilder(1040, 1040),
    $response['actions']
);

$message->add( $imagemapMessageBuilder );
$message->add( new TextMessageBuilder( 'Testing Message' ) );

$resp = $bot->replyMessage(
  $recipient,
  $message
);

// Try to check the $resp value, it's 200, no error message
`
The Imagemap delivered to the user, but the text message never came.
Did I missed something?

**Comment by moznion** [comment]
@IronLady 
Sorry for late reply.
I could not reproduce this problem. Could you show us more details (e.g. request and response)?

**Comment by moznion** [comment]
@IronLady If there is no reply within one week, this issue will be closed.
