### ISSUE TITLE
PostbackTemplateActionBuilder in wrong key

### ISSUE THREAD

**Issue by irmannmal** [line/line-bot-sdk-php#45]
**PostbackTemplateActionBuilder.php**

`public function buildTemplateAction(){`
`return [`
`'type' => ActionType::POSTBACK,`
`'label' => $this->label,`
`'data.json' => $this->data`
`];`
`}`

> will work if replace **data.json** with **data**

**PostbackEvent.php**

`public function getPostbackData(){`
`return $this->event['postback']['data.json'];`
`}`

> will work if replace **data.json** with **data**

**Comment by ncwgf** [comment]
Seem like you modify this SDK source code your own
There are no related result when search in this repo by keyword 'data.json'

**Comment by irmannmal** [comment]
@ncwgf its mean solved

**Comment by moznion** [comment]
@irmannmal Hi. If this problem has been already solved, please close this issue.

**Comment by irmannmal** [comment]
@moznion ok, thanks to remind

**Comment by moznion** [comment]
Thank you!
