### ISSUE TITLE
is that possible to update session data everytime callbacked or everytime bot has replyed message?

### ISSUE THREAD

**Issue by kelvinhalim13** [line/line-bot-sdk-php#46]
Hello, im using codeigniter to use BOT, and i want trying to use session as key for reply message. So everytime my bot has reply a message the last session should be updated.

I do this because, im trying to prevent to reply same text with same keyword

heri is my code : 

        $bot = new \LINE\LINEBot(
            new \LINE\LINEBot\HTTPClient\CurlHTTPClient($reply_token),
            ['channelSecret' => $secret]
        );
        if(isset( $_SESSION['count']){
            $count = $_SESSION['count'];
        }else{
            $count = 0
        }

        $signature = $_SERVER["HTTP_".\LINE\LINEBot\Constant\HTTPHeader::LINE_SIGNATURE];
        $body = file_get_contents("php://input");

        $events = $bot->parseEventRequest($body, $signature);
        foreach ($events as $event) {
            if ($event instanceof \LINE\LINEBot\Event\MessageEvent\TextMessage) {
                $reply_token = $event->getReplyToken();

                $text = strtolower($event->getText());
                if($text == 'hi'){
                    $reply_message = $items[array_rand($items)];
                    $bot->replyText($reply_token, $reply_message);
                }else if ($text == 'makanya belajar'){
                    $reply_message = $teach[array_rand($teach)];
                    $bot->replyText($reply_token, $reply_message);
                }else if($text == 'vin' || $text == 'zi' || 'vinzi'){
                    if($count != 6){
                        $_SESSION['count'] += 1;
                        $reply_message = $name[$count];
                        $bot->replyText($reply_token, $reply_message);

                    }else{
                        $reply_message = $name[$count];
                        unset($_SESSION['count']);
                        $bot->replyText($reply_token, $reply_message);
                    }
                }
            }
        }

before i tried to use it, i try to `var_dump` all the session and refresh my callback funtion, i could get the result what i want.  but after i tried chat my bot, he always send the same text. thak you

**Comment by ncwgf** [comment]
You should use your own way to store the status, e.g. database or a file

**Comment by moznion** [comment]
@kelvinhalim13

I think the same as @ncwgf.
You should not use `$_SESSION` because sender of callback is LINE server, not LINE user. Please use `userId` as identifier of user and store that into storage as you like.

**Comment by sprabowo** [comment]
@kelvinhalim13 

i just use file txt to save session. keep it in dir/sessions_userId.txt

**Comment by moznion** [comment]
I will close the issue for now. If you have more question, please reopen this.
