### ISSUE TITLE
Validating channel access.

### ISSUE THREAD

**Issue by hermandinho** [line/line-bot-sdk-php#49]
Hello and thanks for this great sdk. Please is it possible to check if a combination of Channel Secret and Channel Access Token are valid. Hope my question as well asked. That is, is there an endpoint which requirs say these 2 keys and returns a response wheater they are valid or not?

Regards.

**Comment by GuitarSucks** [comment]
Sorry we dont have such API to confirm them.
Can you provide us the use case so we can consider it?

**Comment by moznion** [comment]
@hermandinho If there is no reply within one week, this issue will be closed.

**Comment by hermandinho** [comment]
Sory for the delay. @GuitarSucks i don't understand very well what you mean by use case. May be in french would be easier for me to understand.

**Comment by kazuki-ma** [comment]
There are no validation API.

I think just testing reply is enough.
If you have reason of validation independently(_use-case_ = utilisation), please let us know.
