### ISSUE TITLE
How to find TargetMID ?

### ISSUE THREAD

**Issue by b3nyariel** [line/line-bot-sdk-php#5]
in /example/SendingSample/setting.php

return [
    'channelId' => 'xxx', // I see
    'channelSecret' => 'xxx', // I see
    'channelMid' => 'xxx', // I see
    'targetMid' => '???', // here I don't know, where I can found it?
];

**Comment by justinushermawan** [comment]
How to get user mid?

**Comment by b3nyariel** [comment]
yes, because.. I try with userID or phone number.. return 'invalid user'.

**Comment by moznion** [comment]
There is no way to get user MID actively. However passively can do that.

MID information is contained request payload from user (i.e. bot's friend).
Example: https://github.com/line/line-bot-sdk-php/blob/d68105b3d124397e28f686c63b2ad96a89c8ae88/examples/EchoBot/src/routes.php#L48

Please refer [official documentation](https://developers.line.me/bot-api/api-reference) and [echo bot sample](https://github.com/line/line-bot-sdk-php/tree/master/examples/EchoBot).

**Comment by justinushermawan** [comment]
Is there another ways to get the list of bot's friends in order that I can get their mid?

**Comment by moznion** [comment]
Unfortunately no. The friend list API is not provided.
You should keep user's information when received [added as friend event](https://developers.line.me/bot-api/api-reference#receiving_operations_params).

**Comment by justinushermawan** [comment]
I have tried it, but why when there is someone added the BOT as friend, the callback URL is not called?
