### ISSUE TITLE
Asking how to do new line / new bubble chat in line chatbot

### ISSUE THREAD

**Issue by rebornishard** [line/line-bot-sdk-php#52]
How to do that i tried with ('\n') but it fail,
or is there anything I can do to make a new bubble chat for reply user message

example 1 , new line

Hello,
I am bot

example 2, new bubble

-----bubble 1

Hello

----- 
-----bubble 2

I am bot

------

**Comment by moznion** [comment]
Could you use `"\n"` instead of `'\n'`?

**Comment by rebornishard** [comment]
@moznion lol sry forgot to mention `"\n"`
worked like a charm

is there any clue for new bubble ?
let me try call replyText twice

thank you

**Comment by moznion** [comment]
@rebornishard 
You can reply multi messages up to 5 (please see: https://devdocs.line.me/en/#reply-message).
This SDK provides helper method to do that. Please refer [MultiMessageBuilder](https://github.com/line/line-bot-sdk-php/blob/e16d9ca416fcdc9c373a1b155b9fe521f99b6b1b/src/LINEBot/MessageBuilder/MultiMessageBuilder.php).

**Comment by rebornishard** [comment]
thanks, gotten into that,
i tried with 2 bots, 1 success, 1 fail
another one fail in TextMessageBuilder
`string(100)` "{"message":"The property, 'messages[0].text', in the request body is invalid (line: 1, column: 84)"}"``

**Comment by moznion** [comment]
@rebornishard 
I could not reproduce this problem. Could you show us more details?

**Comment by moznion** [comment]
@rebornishard If there is no reply within one week, this issue will be closed.

**Comment by rebornishard** [comment]
@moznion i use webhook from my other project and worked,
sry for late reply i must rebuild it from scratch, no problem after running it for 3 days

and now i want to try MultiMessageBuilder

can i use it like this 

text
image
text
audio
text

with MultiMessageBuilder ?

thank you @moznion

**Comment by moznion** [comment]
Please refer: https://github.com/line/line-bot-sdk-php/blob/e16d9ca/tests/LINEBot/SendMultiMessageTest.php#L80

**Comment by moznion** [comment]
And please refer to the wiki page: https://github.com/line/line-bot-sdk-php/wiki/Sending-multiple-messages
