### ISSUE TITLE
Asking how to use this sdk in localhost

### ISSUE THREAD

**Issue by ferdi554** [line/line-bot-sdk-php#53]
i try to use this sdk in localhost, but i getting error SSL certificate problem: unable to get local issuer certificate.

**Comment by GuitarSucks** [comment]
Hi @ferdi554 
Your question is not actually related to SDK , but on the usage of Messaging API.
Basically you need to have a server with SSL certificate to make communication with our platform.

> The SSL certificate must be issued by an authorized CA (authorized CA). If a self-issued SSL certificate is applied to your server, requests sent from the LINE platform will fail.
> https://developers.line.me/wp-content/uploads/2016/04/ca_root.txt

- If your looking for free SSL you can use Let’s Encrypt and StartSSL.
- If you want to try it out SDK without the settings, you can use Heroku.
