### ISSUE TITLE
How to use emoticons unicode in LINE API ?

### ISSUE THREAD

**Issue by ekojs** [line/line-bot-sdk-php#54]
let's I want to use this emoticon `0x100005`, how to do that in PHP ?

**Comment by ekojs** [comment]
the documentation not clear enough, can you please show example code how to use line api ?

i wan to reply with confirm message using this parameter :
```php
array(
	'replyToken' => $event['replyToken'],
	'messages' => array(
		'type' => 'template',
		'altText' => 'this is a confirm template',
		'template' => array(
			'type' => 'confirm',
			'text' => 'Are you sure?',
			'actions' => array(
				array(
					'type' => 'postback',
					'label' => 'Yes',
					'data' => 'btnyes',
					'text' => 'yes'
				),
				array(
					'type' => 'postback',
					'label' => 'No',
					'data' => 'btnno',
					'text' => 'no'
				)
			)
		)
	)
)
```
but it show nothing in reply messages. What's wrong ?

**Comment by moznion** [comment]
> let's I want to use this emoticon 0x100005, how to do that in PHP ?

Probably that is not a question about this SDK, that is a PHP question (So originally we don't have responsibility to answer that).

Please try this;

```php
$code = '100005';
$bin = hex2bin(str_repeat('0', 8 - strlen($code)) . $code);
$emoticon =  mb_convert_encoding($bin, 'UTF-8', 'UTF-32BE');
```

And second question is unrelated to this SDK.
