### ISSUE TITLE
VideoMessageBuilder cant save and forward

### ISSUE THREAD

**Issue by sprabowo** [line/line-bot-sdk-php#56]
i've just used VideoMessageBuilder for reply 

```php
$p2 = "https://url/1.mp4";
$p1 = "https://url/1.jpg";
$this->bot->replyMessage($replyToken, new VideoMessageBuilder($p2,$p1));
```

it success. i cant download the video and forward it. is there any information i missed about this feature?

**Comment by moznion** [comment]
(markdown prettify)

**Comment by moznion** [comment]
I cannot suggest you anymore because information is lacked.

Please more information;

1. More code of your bot
2. Detail of symptoms
3. Actual video files and thumbnails

And I have a question; is this a bug (or possibility of bug) of this SDK or not?

**Comment by sprabowo** [comment]
@moznion 
![photo_2017-02-15_17-29-04](https://cloud.githubusercontent.com/assets/11748183/22970326/5303eb74-f3a4-11e6-84ec-976bcc50137a.jpg)
when i want to forward video from bot, i cant. this is not bug. maybe feature that is limited by LINE like LINE don't support gif. is this issue can be suggested to LINE?

**Comment by moznion** [comment]
I cannot judge what this is an issue of the LINE because actual the video file and thumbnails file is not shown us. More code and files please.

**Comment by sprabowo** [comment]
i just use textmessage handler from example
`
if($text=='kokou')
{
$p2 = "https://url/1.mp4";
$p1 = "https://url/1.jpg";
$this->bot->replyMessage($replyToken, new VideoMessageBuilder($p2,$p1));
}
`
![photo_2017-02-15_17-52-57](https://cloud.githubusercontent.com/assets/11748183/22971226/9d3210c4-f3a7-11e6-8323-b2bd6b262c65.jpg)
video from url can be played untill end but i cant forward the video to another chat. its different with ImageMessageBuilder, when i get replied image (not imagemap) i can forward and save the image.

**Comment by moznion** [comment]
Let's organize your problem.

- Delivering and playing the video has been succeeded
- Context menu of "keep" and "forward" are unavailable

I asked this problem to the part of bot API, it turned out the behavior is specification.
It means, "video that is from a bot cannot forward and keep".
This is a spec of the LINE. It's not an issue of VideoMessageBuilder.
