### ISSUE TITLE
Methods of Event class are not suggested

### ISSUE THREAD

**Issue by mitsuoka0423** [line/line-bot-sdk-php#581]
The PHPDoc for the getEvents method in the ParsedEvents class is set to array, which prevents autocompletion from suggesting methods of the Event class.

https://github.com/line/line-bot-sdk-php/blob/2ab68efa24327cd1ab418142f4b0b00d3d004fc4/src/parser/lib/ParsedEvents.php#L53

## Environment 

- Device
  - MacBook Air:  M1, 2020
  - OS: macOS Venture 13.6.3（22G436）
- Editor
  - VSCode:  1.87.2
  - Extension
    - https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client

**Comment by Yang-33** [comment]
You can use the fixed sdk from https://github.com/line/line-bot-sdk-php/releases/tag/9.7.1. Thank you for report.
