### ISSUE TITLE
Could i get user information such as name using getUserId() ?

### ISSUE THREAD

**Issue by kelvinhalim13** [line/line-bot-sdk-php#61]
Hello, i have little problem on user information, I have found some LINE BOT tutorial how to get the user name, but i always found they using LINE_CHANNEL_MID.

Unfortunately i don't have LINE_CHANNEL_MID in my BOT basic information. I only have Channel ID, Channel Secret, And Channel Access token. I don't know why i don't have it.

But all is find, i can get the text from user, get the user_id, room_id or group_id and i could send reply message to the user.

     ` $bot = new \LINE\LINEBot(
            new \LINE\LINEBot\HTTPClient\CurlHTTPClient('channel_access_token'),
            ['channelSecret' => 'channel_secret']
        );
        $signature = $_SERVER["HTTP_".\LINE\LINEBot\Constant\HTTPHeader::LINE_SIGNATURE];
        $body = file_get_contents("php://input");
        $events = $bot->parseEventRequest($body, $signature);
        foreach ($events as $event) {
            if ($event instanceof \LINE\LINEBot\Event\MessageEvent\TextMessage) {
                $reply_token = $event->getReplyToken();
                $user_id = $event->getUserId();

                //i want trying to get the user information like the user name, so i could send the name as reply message
          
            } 
        }'

could i get the user information by the user_id?

thank you

**Comment by moznion** [comment]
Please use `\LINE\LINEBot#getProfile()`. See: https://github.com/line/line-bot-sdk-php/blob/73b50e6/src/LINEBot.php#L68

**Comment by moznion** [comment]
And wiki-ed => https://github.com/line/line-bot-sdk-php/wiki/Getting-user-profile

**Comment by ryrun168** [comment]
@moznion can we get user id by phone number or email address?

**Comment by kelvinhalim13** [comment]
@ryrun168 i think we couldnt, Because its privacy. every user has their own right privacy.
