### ISSUE TITLE
is it possible to check all the user who is reading the message in group / room chat?

### ISSUE THREAD

**Issue by kelvinhalim13** [line/line-bot-sdk-php#62]
i need to get the user list, who is reading the message but i didnt find any tutorial for this. Can you help me?

**Comment by moznion** [comment]
Unfortunately Messaging API doesn't provide the way to do that.

**Comment by kelvinhalim13** [comment]
so, will this featured will be available ?

**Comment by GuitarSucks** [comment]
@kelvinhalim13 
Sorry no plans at this moment

**Comment by rebornishard** [comment]
+1 for this

sry to reply in this thread, might be pointless to open a new one,
using line bot sdk php on group chat, is there any guide to do that ?
thanks
