### ISSUE TITLE
Could send ImageMessage but not ImageMap

### ISSUE THREAD

**Issue by anz507** [line/line-bot-sdk-php#63]
In the chat window it says "Unable to load photo." and a button try again
Here are my code snippet
```$baseSizeBuilder = new \LINE\LINEBot\MessageBuilder\Imagemap\BaseSizeBuilder(746,745);
$imagemapUriActionBuilder = new \LINE\LINEBot\ImagemapActionBuilder\ImagemapUriActionBuilder(
            'https://this.is.just.placeholder/',
            new \LINE\LINEBot\ImagemapActionBuilder\AreaBuilder(0,0,560,120)
        );
$imagemapMessageActionBuilder = new \LINE\LINEBot\ImagemapActionBuilder\ImagemapMessageActionBuilder(
            'Some Tag Line',
            new \LINE\LINEBot\ImagemapActionBuilder\AreaBuilder(0,120,560,120)
        );
$ImageMapMessageBuilder = new \LINE\LINEBot\MessageBuilder\ImagemapMessageBuilder(
    'https://this.image.is.working.on.imagemessagebuilder.but.not.here',
    'Text to be displayed',
    $baseSizeBuilder,
    [
        $imagemapUriActionBuilder,
        $imagemapMessageActionBuilder
    ]
);

$response = $bot->replyMessage($event->getReplyToken(), $ImageMapMessageBuilder);```

Did I miss something? 
The url is working just fine

**Comment by kazuki-ma** [comment]
Do you have access logs in your server?

Please note. URI in `ImageMapMessage` is different from the accessed URI from client.
URI in`ImageMapMessage` called [Base URL](https://devdocs.line.me/en/#base-url) and client add preferred image width as suffix like `baseurl/1040`.

**Comment by anz507** [comment]
I do, but no exception caught and the message is sent. 
So, is the Base URL is a URL that does not ends with file extension but returning an image?

**Comment by kazuki-ma** [comment]
If you send `https://your.domain/path/file_name.png` as Base URL.
Client will access `https://your.domain/path/file_name.png/1040`.

To ignore resolution suffix for debug purpose, add `?_ignore=` to your Base URL like `https://your.domain/path/file_name.png?_ignored=`

**Comment by anz507** [comment]
Thank you for the answer!
It's working
