### ISSUE TITLE
Cann't get message type for non text message

### ISSUE THREAD

**Issue by mgilangjanuar** [line/line-bot-sdk-php#65]
I can not get the attribute ```message['type']``` with method ```getMessageType()``` on the ```event``` object when a user sends a sticker or a non text message. And my server did not record any error. Is this a bug in the SDK or in the API?

**Comment by moznion** [comment]
I couldn't reproduce such symptom. Please show us more detail code.
(Probably this is not a bug of SDK and API)

**Comment by moznion** [comment]
And I suggest you, aren't you using older version SDK? This feature is available after version 1.3.0.

**Comment by mgilangjanuar** [comment]
Ah ya you're right. Problem solved with update composer. Thanks.
