### ISSUE TITLE
ImageMessageBuilder show in Mobile, But Not in PC

### ISSUE THREAD

**Issue by kelvinhalim13** [line/line-bot-sdk-php#66]
if(preg_match('(\bflip card\b)', $text) != 0 || preg_match('(\bflip a card\b)', $text) != 0){
           $image = base_url("/asset/card/".$this->flip_card().".png");
           $card = new \LINE\LINEBot\MessageBuilder\ImageMessageBuilder(
			$image,
			$image
           );
          $bot->replyMessage($reply_token, $card);
    }

In Phone i could see the images, But in LINE PC the images are not showed and they didn't stop loading

Pc site :
![line_image](https://cloud.githubusercontent.com/assets/23371895/23933512/9fe2f89e-0971-11e7-9d38-e6e4e1c045c8.PNG)

The image work find in mobile
![line_image2](https://cloud.githubusercontent.com/assets/23371895/23933567/01a28e78-0972-11e7-9c0d-a7f5714f0e72.png)

Is this the right place i share this problem here?

**Comment by rebornishard** [comment]
Preview image URL (Max: 1000 characters)
HTTPS
JPEG
Max: 240 x 240
Max: 1 MB

image size not more than 240*240 ?

**Comment by kelvinhalim13** [comment]
this is my link :
https://vinzi.id/asset/card/1.png

the images size is 72*96 only @rebornishard

**Comment by kelvinhalim13** [comment]
the image type must be JPEG?

**Comment by sprabowo** [comment]
@kelvinhalim13 i think you should resize your image to be 240px x 240px (maybe there is space in left or right, keep it white background) with extension .jpg (must)

**Comment by kelvinhalim13** [comment]
@rebornishard  @sprabowo still doenst work 

i have using third party to showing the images and i have try resize the images are still keep loading

**Comment by kelvinhalim13** [comment]
new method how i call my image 
https://vinzi.id/image/image/card/1?w=120

**Comment by infinitylabs** [comment]
might be unrelated but using the python library I have the same issue. All images are formatted properly according to the API and show up fine on mobile, tablet, chromeapp; but on any desktop version they load eternally. 

Desktop is very behind in terms of features so I wasnt sure if it was just an issue with the client.

**Comment by kelvinhalim13** [comment]
any idea?

**Comment by moznion** [comment]
Discussion of related topic is under way on here: https://github.com/line/line-bot-sdk-python/issues/36#issuecomment-300416400

Please see the above.

**Comment by kelvinhalim13** [comment]
i think will closed the issue. i will keep updated with the above issue
