### ISSUE TITLE
Cannot reissuing the access token

### ISSUE THREAD

**Issue by ipol2n** [line/line-bot-sdk-php#7]
Hi,

I have a business connect account but my channel access token have just expired.

I tried to reissue the access token followed this doc https://developers.line.me/restful-api/overview#refresh_token but I got this result

> {
>   "statusCode": "411",
>   "statusMessage": "TOKEN_INVALID_TOKEN"
> }

Do you have any idea?

**Comment by naari3** [comment]
In my case, it is simply token and mid are mistake.
I'm checking and correcting them, I was able to avoid errors.

**Comment by moznion** [comment]
I think so that.
