### ISSUE TITLE
Webhook Configuration failed for Sub-Level Domain

### ISSUE THREAD

**Issue by arthiverticurl** [line/line-bot-sdk-php#77]
Hi,
I am not sure this is right place to raise my issue regarding Webhook config. Currently integrating Line app using PHP. Under Message API, when configuring sub domain path in Webhook it throws an error such as "could not connect SSL" though domain is SSL certificate. But if give Top level domain it accepts and Line gives responses whenever user any activities on official account.
![2017-05-09_220218](https://cloud.githubusercontent.com/assets/12858554/25861915/d9ed1f52-3503-11e7-90c8-3e158764c2fb.jpg)
![2017-05-09_220034](https://cloud.githubusercontent.com/assets/12858554/25861916/d9f45c18-3503-11e7-9248-c1e881f8db6e.jpg)

And also please suggest the right channel to communicate Line Tech team.

**Comment by moznion** [comment]
This issue is not related to this SDK.

FYI: I suggest you to check and verify your SSL certification and the configuration. We have good tools: https://www.ssllabs.com/ssltest/

**Comment by arthiverticurl** [comment]
Hi Moznion,

 

Thank you for your immediate response.

 

Will check our server SSL config in below tool.

 

Best Regards,

 

ARTHI R | Marketing Automation Specialist

 

VERTICURL | A WPP COMPANY

Navkar Chambers, #227-A, Thiruvenkatasamy Road (East), R.S. Puram | Coimbatore 641002 | India

Email ID : arthi.rathinaswamy@verticurl.com

Web      :   <http://www.verticurl.com/> www.verticurl.com

Twitter   :   <http://www.twitter.com/Verticurl> www.twitter.com/Verticurl

Privileged/Confidential Information may be contained in this message. If you are not the addressee indicated in this message, you should destroy this message. For more information on WPP's business ethical standards and corporate responsibility policies, please refer to WPP's website.
