### ISSUE TITLE
[QA] How i can send Link Message?

### ISSUE THREAD

**Issue by liverbool** [line/line-bot-sdk-php#83]
I'm looking in https://developers.line.me/link-messages/link-messages#open_page but can't find where that link/page appear.

And seem this repo has not something like `LinkMessageBuilder`.

PS. My account is none paid type.

**Comment by GuitarSucks** [comment]
Hi,
Unfortunately this API is only for some few partners and is not available publicly. Sorry for the confusion and will update the docs appropriately.
