### ISSUE TITLE
read time out and empty reply

### ISSUE THREAD

**Issue by sandmanzz** [line/line-bot-sdk-php#84]
it have been 1 weeks i never open my bot, but yesterday suddenly my bot does not work. when i try webhook from line developer it always return "read timeout" or sometime return empty reply

**Comment by moznion** [comment]
Could you show me log of your bot?

In my opinion, probably this is not LINE bot (and SDK) issue. Does your httpd work rightly? Network too?

**Comment by sandmanzz** [comment]
![image](https://user-images.githubusercontent.com/21254367/27008810-1f287fc8-4ea7-11e7-86d7-81970de57c2a.png)

it show invalid replytoken but im not sure because it work correctly work

**Comment by moznion** [comment]
That is spec. Reply token that is contained in request payload of Webhook URL verifying is not available for API calling.

![img_5796](https://user-images.githubusercontent.com/1422834/27008867-6380d17c-4eb9-11e7-954a-7aa86d1ba70d.JPG)

> Note: The dummy webhook contains a reply token, but you cannot use it to call Reply API.

It looks there is no symptoms that described at this issue description, so I close this.
