### ISSUE TITLE
can't play audio from my server who have https

### ISSUE THREAD

**Issue by fataelislami** [line/line-bot-sdk-php#85]
my bot couldn't play audio message 
the link is https://shopagansta.com/line/kajian/doa.m4a 

but if i upload to google sites, it can

is there error from my server ? how to check?

**Comment by nekonynn** [comment]
If it's working, when you click the link of the audio site, it'll be automatically downloaded.

If it's not, probably there's a problem with your SSL certificate, because I can't either access it [here](https://nekonynn.s-ul.eu/o7NPEZxr).

**Comment by fataelislami** [comment]
i have change it, but still can't play
check this link audio for test
https://islamify.id/audio/testaudio.m4a

**Comment by Vaduz** [comment]
I couldn't get what is the problem with this SDK.  Can I elaborate?

**Comment by Vaduz** [comment]
If you still have questions, please refer to the faq.
https://github.com/line/line-bot-faq
