### ISSUE TITLE
Upgrade to Guzzle 6.2

### ISSUE THREAD

**Issue by achimha** [line/line-bot-sdk-php#9]
The current version of Guzzle is 6.2 and it has numerous incompatible API changes. The problem with PHP composer is that you can only install one version of a package and by installing this one, it is not possible to install any package written against Guzzle 6.

**Comment by nanangkoesharwanto** [comment]
>composer require linecorp/line-bot-sdk
Using version ^0.1.0 for linecorp/line-bot-sdk
./composer.json has been updated
> php artisan clear-compiled
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

Problem 1
    - Installation request for linecorp/line-bot-sdk ^0.1.0 -> satisfiable by linecorp/line-bot-sdk[0.1.0].
    - Conclusion: remove guzzlehttp/guzzle 6.2.1
    - Conclusion: don't install guzzlehttp/guzzle 6.2.1
    - linecorp/line-bot-sdk 0.1.0 requires guzzlehttp/guzzle ^5.3 -> satisfiable by guzzlehttp/guzzle[5.3.0, 5.3.1].
    - Can only install one of: guzzlehttp/guzzle[5.3.0, 6.2.1].
    - Can only install one of: guzzlehttp/guzzle[5.3.1, 6.2.1].
    - Installation request for guzzlehttp/guzzle == 6.2.1.0 -> satisfiable by guzzlehttp/guzzle[6.2.1].

Installation failed, reverting ./composer.json to its original content.

How to solve this problem? Thank a lot.

**Comment by moznion** [comment]
Sorry, old API is abandoned.
Please new API with the latest SDK (v1.0.0).
