### ISSUE TITLE
How to use Template Message Builder?

### ISSUE THREAD

**Issue by hanachan1026** [line/line-bot-sdk-php#91]
I was trying to use pure PHP and curl to use the template message builder but now I want to use this SDK.

Can you show us one example to use Template Message Builder with json or something?

**Comment by moznion** [comment]
Please see [example project](https://github.com/line/line-bot-sdk-php/tree/master/examples), especially this class: https://github.com/line/line-bot-sdk-php/blob/9c62c7c0d0be3df9124abc8a7146d6af36cffd45/examples/KitchenSink/src/LINEBot/KitchenSink/EventHandler/MessageHandler/TextMessageHandler.php

FYI: phpdoc of that class is [here](https://line.github.io/line-bot-sdk-php/class-LINE.LINEBot.MessageBuilder.TemplateMessageBuilder.html).

**Comment by kevinjon27** [comment]
@moznion  I think the carousel is not working? because I tried, and nothing happen.
