### ISSUE TITLE
getProfile() result "Not Found" What are the conditions to acquire?

### ISSUE THREAD

**Issue by YuK1Game** [line/line-bot-sdk-php#92]
```php
$response = $this->objLineBot->getProfile([User ID]);
var_dump($objResponse);
```

result
```php
object(LINE\LINEBot\Response)#33 (3) {
  ["httpStatus":"LINE\LINEBot\Response":private]=>
  int(404)
  ["body":"LINE\LINEBot\Response":private]=>
  string(23) "{"message":"Not found"}"
  ["headers":"LINE\LINEBot\Response":private]=>
  array(12) { ... }
}
```

My account(Bot friend) : OK
Others(Bot friend) : NG
Others(Bot not friend) : NG

What are the conditions to acquire?

**Comment by nekonynn** [comment]
Probably your friend's LINE version is under 7.5.0 so your BOT can not grab their profile ID even if they already added your BOT as your friend.

The condition that needed to be fulfilled to acquire the profile ID:
- Your LINE version must be above 7.5.0
- Has added the bot as your friend to accept Terms of Use

You can read the detail here: https://developers.line.me/messaging-api/obtaining-user-consent

Good luck with your bot, hope this helps

**Comment by YuK1Game** [comment]
I have understood the matter described in your last message.
