### ISSUE TITLE
VideoMessageBuilder could not play in LINE Desktop Client

### ISSUE THREAD

**Issue by kelvinhalim13** [line/line-bot-sdk-php#94]
as same as https://github.com/line/line-bot-sdk-php/issues/66
The video could be played in android, but not in PC

here is my example video file

https://vinzi.id/asset/video/larva-korea.mp4

```
$video = "https://vinzi.id/asset/video/test.mp4";
$preview_image = "https://vinzi.id/asset/images/baka.jpg";
 $video = new VideoMessageBuilder(
     $video,
     $preview_image
 );
$bot->replyMessage($reply_token, $video);
```

I thought same as image, LINE desktop client having problem or bug. I am scared audio file have the same problem too. Please check about this.

And i want to know about the video, is there any limit size of video or minute that we could send the video to the user ?

**Comment by Vaduz** [comment]
Closing because LINE desktop client fixed the issue. (#66 is closed already)
See: https://github.com/line/line-bot-sdk-python/issues/36#issuecomment-300416400
