### ISSUE TITLE
How to get Profile information by sending a Contact to Bot?

### ISSUE THREAD

**Issue by zombozo12** [line/line-bot-sdk-php#97]
I want to get information from sending a contact to my bot. Is that possible? I've sent a contact to my bot but there is no EventRequest. The contact was sent and the server doesn't display the EventRequest. Thanks. Sorry for my bad English.

**Comment by Vaduz** [comment]
As far as I know, there is no such event type defined.
If you still have questions, please refer to the faq.
https://github.com/line/line-bot-faq
